/* ===== Essay Quest v2 data ===== */
const DATA = (() => {
const RAR = [
  {n:'Common',   c:'#c9ced6', m:1.00},
  {n:'Rare',     c:'#4aa3ff', m:1.08},
  {n:'Epic',     c:'#b06cff', m:1.16},
  {n:'Legendary',c:'#ffb52e', m:1.25},
  {n:'Mythical', c:'#ff4d6d', m:1.38}];
const SKILLS = {
  fist:  {n:'Flurry',  d:'3 quick hits at 50% each', cd:2},
  blade: {n:'Cleave',  d:'Hit every enemy for 70%', cd:3},
  pole:  {n:'Impale',  d:'160% damage, ignores guard', cd:3},
  ranged:{n:'Volley',  d:'4 arrows/shots at 40% on random enemies', cd:3},
  heavy: {n:'Smash',   d:'190% damage, 45% chance to stun', cd:4},
  scythe:{n:'Reap',    d:'Hit every enemy for 55%, heal 30% of damage', cd:3},
  katana:{n:'Iaido',   d:'One lightning draw: 145% damage, +35% crit chance, ignores guard', cd:3},
  staff: {n:'Arcane Nova', d:'Hit every enemy for 60%, 30% chance to burn each', cd:3},
  thrown:{n:'Ricochet', d:'5 bounces at 42% across the enemies', cd:3}};
// per world: types [name, archetype, [common, rare, epic, legendary, mythical]]
const WORLDS = [
 {name:'Greenlands', essay:'common', sub:'Common Module · Nineteen Eighty-Four', boss:'The Watcher',
  pal:{sky:['#7cc6ff','#d8f0ff'], far:'#7fbf7a', mid:'#4f9e4c', ground:'#6cc35a', ground2:'#4a9a3e', accent:'#2f6f2c'},
  dungeons:['Sunny Meadow','Whispering Forest','Ruined Watchtower','Mossy Cave','Ministry Keep'],
  types:[['Fists','fist',['Leather Wraps','Iron Knuckles','Thoughtcrime Gauntlets','Fists of the Brotherhood','Hands of Room 101']],
         ['Sword','blade',['Shortsword','Knight’s Longsword','Ministry Blade','Truthbreaker','Doublethink Edge']],
         ['Spear','pole',['Pitchfork','Boar Spear','Prole Pike','Golden Country Spear','Kingslayer Pike']],
         ['Bow','ranged',['Hunting Bow','Longbow','Telescreen Recurve','Chestnut Tree Bow','Eye of Big Brother']],
         ['Club','heavy',['Cudgel','Spiked Mace','Paperweight Maul','Coral Heart Hammer','Ministry of Love Maul']]],
  armour:[['Dented Breastplate','Padded Vest','Novice Robe'],['Chainmail','Ranger’s Coat','Outer Party Overalls'],['Ministry Plate','Thoughtcrime Trenchcoat','Inner Party Suit'],
          ['Golden Country Plate','Brotherhood Shadowcloak','Archivist’s Robe'],['Kingslayer Plate','Doublethink Duster','Robe of Room 101']],
  enemies:['slime','goblin','boar','enforcer','brawler','pwisp'], mini:['captain','oBrien'], bossKey:'watcher'},
 {name:'Storm Coast', essay:'moda', sub:'Module A · The Tempest + Hag-Seed', boss:'Prospero, Storm-Caller',
  pal:{sky:['#5a8fc9','#bfe0f5'], far:'#3f7fb0', mid:'#2d6a96', ground:'#f0d999', ground2:'#d9bd73', accent:'#1f4f78'},
  dungeons:['Golden Beach','Shipwreck Cove','Sea Cave','Jungle Isle','Prospero’s Cell'],
  types:[['Cutlass','blade',['Rusty Cutlass','Boatswain’s Sabre','Corsair’s Cutlass','Prospero’s Rapier','Tempest Blade']],
         ['Harpoon','pole',['Fishing Harpoon','Whaler’s Harpoon','Sea-Witch Harpoon','Sycorax’s Spear','Leviathan Harpoon']],
         ['Flintlock','ranged',['Pocket Pistol','Ship’s Musket','Storm Musket','Ariel’s Lightning Pistol','Thunderclap Hand-Cannon']],
         ['Trident','pole',['Coral Trident','Tide Trident','Neptune’s Fork','Ferdinand’s Trident','Trident of the Drowned Book']],
         ['Anchor','heavy',['Ship’s Anchor','Kraken Anchor','Shipwreck Anchor','Staff-Breaker','Anchor of the Abyss']]],
  armour:[['Barnacle Breastplate','Deckhand Vest','Sailcloth Robe'],['Shell Armour','Pirate Longcoat','Islander’s Wrap'],['Coral Plate','Corsair’s Frock Coat','Spirit-Woven Robe'],
          ['Ferdinand’s Royal Plate','Ariel’s Featherweave','Prospero’s Mantle'],['Leviathan Scale Plate','Storm-Caller’s Greatcoat','Robe of the Drowned Book']],
  enemies:['crab','sprite','drowned','gull','pirate','iboar'], mini:['caliban','arielStorm'], bossKey:'prospero'},
 {name:'Hollow Wastes', essay:'modb', sub:'Module B · T.S. Eliot (hot desert)', boss:'The Shadow',
  pal:{sky:['#f2a65a','#ffe2a8'], far:'#d99a5b', mid:'#b97a45', ground:'#e8c27a', ground2:'#cfa25a', accent:'#7a4b2a'},
  dungeons:['Scorched Dunes','Ash Fields','Ruined Chapel','Bone Pit','Shadow Rift'],
  types:[['Scythe','scythe',['Rusted Scythe','Reaper’s Scythe','Sunscorch Scythe','Shadow-Falls Scythe','Whimper’s End']],
         ['Halberd','pole',['Iron Halberd','Prickly-Pear Halberd','Dune Halberd','Magus Halberd','Halberd of the Dead Land']],
         ['Crossbow','ranged',['Light Crossbow','Repeater Crossbow','Sandstorm Crossbow','Hollow Men’s Arbalest','Bang-and-Whimper']],
         ['Greatsword','blade',['Hollow Greatsword','Fog Greatsword','Sunfire Claymore','Michelangelo Claymore','Dragonslayer']],
         ['Flail','heavy',['Chain Flail','Coffee-Spoon Flail','Wasteland Morningstar','Formulated-Phrase Flail','Universe Disturber']]],
  armour:[['Sandstone Cuirass','Dust Wraps','Pilgrim’s Robe'],['Bronze Scale','Nomad Leathers','Prayer Shawl'],['Sunforged Plate','Mirage Trenchcoat','Chapel Vestments'],
          ['Magi Plate','Wanderer’s Silk Suit','Vestments of the Magi'],['Kingslayer Sunplate','Mermaid-Song Cloak','Shroud of the Shadow']],
  enemies:['scarecrow','husk','vulture','hound','sgolem','bandit'], mini:['fogcat','hollowKing'], bossKey:'shadow'},
 {name:'Icelands', essay:'modc', sub:'Module C · Name Sign', boss:'Nightfall Wyrm',
  pal:{sky:['#9fd6f0','#f1fbff'], far:'#c8e4f2', mid:'#a6cfe4', ground:'#f4fbff', ground2:'#d5e9f3', accent:'#5a8fb0'},
  dungeons:['Snowy Tundra','Ice Cave','Frozen Lake','Aurora Peak','Old Owl Barn'],
  types:[['Ice Claws','fist',['Frost Talons','Barn-Owl Talons','Snowstorm Claws','Nightfall Talons','Owl-Blind Claws']],
         ['Glacier Blade','blade',['Icicle Sword','Glacier Edge','Aurora Blade','Wisp-Haired Judge','Forty Winters']],
         ['Frost Lance','pole',['Ice Lance','Aurora Lance','Polar Lance','Name-Sign Lance','Truly Named Lance']],
         ['Rimebow','ranged',['Snow Bow','Blizzard Bow','Rime Recurve','Polar Star Bow','Early-Sun Bow']],
         ['Mammoth Maul','heavy',['Ice Hammer','Mammoth Maul','Avalanche Maul','Glacier Breaker','World-Ender Maul']]],
  armour:[['Ice-Crusted Plate','Fur Parka','Woollen Robe'],['Glacier Mail','Snowcloak','Hearthkeeper’s Robe'],['Frostforged Plate','Aurora Leathers','Frost-Weave Robe'],
          ['Nightfall Plate','Owl-Feather Cloak','Robe of the Truly Named'],['Kingslayer Iceplate','Barn-Owl Mantle','Aurora Aegis Robe']],
  enemies:['wolf','golem','owl','yeti','iwisp','sgoblin'], mini:['winterOwl','troll'], bossKey:'wyrm'}];

// legendary / mythical specials by archetype (ability ids are resolved in core)
const LEG = {fist:['double',30], blade:['lifesteal',15], pole:['execute',60], ranged:['crit',30], heavy:['stun',25], scythe:['lifesteal',20]};
const MYTH = {fist:[['double',45],['burn',35]], blade:[['lifesteal',25],['chain',50]], pole:[['execute',90],['pierce',0]],
              ranged:[['crit',40],['multishot',1]], heavy:[['stun',35],['quake',30]], scythe:[['lifesteal',30],['burn',40]]};
const MYTH_DOWN = [['maxhp',10],['fragile',12],['clumsy',6],['selfburn',8],['slowskill',1]];
const ARM_ROLE = ['plate','leather','robe'];
// ---------- Legends: every Legendary / Mythical piece is a named relic from myth ----------
// [key, name, kind, arch|role, rar, origin, lore, abilities, downside, fx]
const LEGENDS = [
 ['zeus_gauntlets','Gauntlets of Zeus','weapon','fist',3,'Greek','Forged by the Cyclopes so the king of the gods could hold the storm in his fists.',[['double',30],['chain',30]],null,'thunder'],
 ['heracles_cestus','Cestus of Heracles','weapon','fist',3,'Greek','The boxing straps Heracles wore for his twelve labours. Each punch lands like a lion’s paw.',[['double',35],['stun',15]],null,'lion'],
 ['zeus_bolt','Thunderbolt of Zeus','weapon','fist',4,'Greek','Not a gauntlet. The bolt itself. Every strike calls lightning from a clear sky.',[['chain',70],['crit',25],['double',20]],['fragile',10],'thunder'],
 ['prometheus_hands','Hands of Prometheus','weapon','fist',4,'Greek','The hands that stole fire from Olympus. They never stopped burning.',[['burn',45],['double',40]],['selfburn',8],'fire'],
 ['harpe','Harpe of Perseus','weapon','blade',3,'Greek','The hooked sword that took Medusa’s head. Wounded foes turn to stone.',[['execute',50],['lifesteal',10]],null,'gorgon'],
 ['excalibur','Excalibur','weapon','blade',3,'Arthurian','Drawn from the stone by the one true king. Its light heals the hand that holds it.',[['lifesteal',15],['crit',20]],null,'holy'],
 ['ares_sword','Sword of Ares','weapon','blade',4,'Greek','The war god’s blade drinks blood and burns with battle-fury.',[['lifesteal',25],['burn',40],['double',20]],['fragile',12],'blood'],
 ['gram','Gram, the Dragon-Slayer','weapon','blade',4,'Norse','Shattered, then reforged by Sigurd to slay the dragon Fáfnir. Runes blaze along its seam.',[['execute',80],['chain',40]],['maxhp',10],'rune'],
 ['achilles_spear','Spear of Achilles','weapon','pole',3,'Greek','Ash-wood from Mount Pelion. Only Achilles could wield it, and it never missed a weak point.',[['execute',60],['crit',15]],null,'bronze'],
 ['gae_bolg','Gáe Bolg','weapon','pole',3,'Irish','Cú Chulainn’s barbed spear: thirty barbs open inside every wound.',[['pierce',0],['lifesteal',12]],null,'barbs'],
 ['poseidon_trident','Trident of Poseidon','weapon','pole',4,'Greek','The Earth-Shaker. One strike and the sea rises with it.',[['quake',40],['stun',25]],['slowskill',1],'wave'],
 ['gungnir','Gungnir, Spear of Odin','weapon','pole',4,'Norse','Carved with runes by the dwarves. Once thrown, it cannot miss.',[['pierce',0],['crit',40],['execute',60]],['maxhp',10],'rune'],
 ['artemis_bow','Bow of Artemis','weapon','ranged',3,'Greek','A silver crescent strung with moonlight by the goddess of the hunt.',[['crit',30],['multishot',1]],null,'moon'],
 ['odysseus_bow','Bow of Odysseus','weapon','ranged',3,'Greek','No suitor could string it. Its arrow flew through twelve axe-heads.',[['crit',25],['pierce',0]],null,'bronze'],
 ['apollo_bow','Sunbow of Apollo','weapon','ranged',4,'Greek','Every arrow is a ray of the sun god’s chariot.',[['crit',40],['burn',40],['multishot',1]],['selfburn',8],'sun'],
 ['gandiva','Gandiva, Bow of Arjuna','weapon','ranged',4,'Hindu','The divine bow of the Mahabharata. Its arrows split into a storm.',[['multishot',1],['chain',50],['crit',30]],['fragile',12],'divine'],
 ['dragon_scroll','Scroll of Dragon’s Breath','weapon','ranged',4,'Chinese','Written in the blood of a sky-dragon. Read it aloud and the dragon answers in fire.',[['burn',60],['multishot',1],['quake',20]],['selfburn',8],'dragonfire'],
 ['heracles_club','Club of Heracles','weapon','heavy',3,'Greek','An olive tree torn out by the roots. It flattened the Nemean Lion’s cave.',[['stun',30],['double',15]],null,'lion'],
 ['hephaestus_hammer','Hammer of Hephaestus','weapon','heavy',3,'Greek','The smith-god’s hammer, still glowing from the forge under Etna.',[['stun',25],['burn',30]],null,'fire'],
 ['mjolnir','Mjölnir','weapon','heavy',4,'Norse','Thor’s hammer. Every blow is a thunderclap that leaps from foe to foe.',[['quake',35],['chain',50],['stun',30]],['clumsy',6],'thunder'],
 ['dagda_club','Club of the Dagda','weapon','heavy',4,'Irish','One end kills nine men; the other brings the dead back to life.',[['quake',40],['lifesteal',20]],['slowskill',1],'life'],
 ['kronos_sickle','Sickle of Kronos','weapon','scythe',3,'Greek','The adamantine sickle the Titan used to overthrow the sky. Time bends around it.',[['lifesteal',20],['execute',40]],null,'time'],
 ['morrigan_scythe','Scythe of the Morrígan','weapon','scythe',3,'Irish','The phantom queen’s blade. Ravens gather wherever it swings.',[['lifesteal',20],['crit',20]],null,'raven'],
 ['thanatos_scythe','Scythe of Thanatos','weapon','scythe',4,'Greek','Death’s own blade. It does not cut flesh; it collects souls.',[['lifesteal',35],['execute',60]],['maxhp',10],'soul'],
 ['hades_reaper','Reaper of Hades','weapon','scythe',4,'Greek','Lord of the Underworld’s harvest blade, burning with the cold fire of the Styx.',[['lifesteal',30],['chain',40],['burn',25]],['fragile',12],'underworld'],
 ['achilles_armour','Armour of Achilles','armour','plate',3,'Greek','Forged overnight by Hephaestus. Bronze, gold and a war-crest that terrified Troy.',[['thorns',20],['ward',8]],null,'bronze'],
 ['athena_aegis','Aegis of Athena','armour','plate',3,'Greek','Bears the Gorgon’s face. Enemies who strike it feel their arms turn to stone.',[['thorns',15],['ward',12]],null,'gorgon'],
 ['ares_armour','Armour of Ares','armour','plate',4,'Greek','Spiked crimson plate that burns hotter the longer the battle lasts.',[['ward',18],['thorns',30]],['clumsy',6],'blood'],
 ['talos_shell','Bronze Shell of Talos','armour','plate',4,'Greek','The giant bronze guardian of Crete. Divine ichor glows in its single vein.',[['ward',22],['thorns',20]],['clumsy',8],'forge'],
 ['fafnir_scale','Dragonscale of Fáfnir','armour','plate',4,'Norse','Cut from the dragon Sigurd slew. Each scale is harder than steel and still warm.',[['ward',20],['thorns',25],['regen',2]],['clumsy',8],'dragonfire'],
 ['nemean_hide','Nemean Lion Hide','armour','leather',3,'Greek','No blade could pierce the lion Heracles strangled. Now you wear it.',[['evasion',10],['ward',10]],null,'lion'],
 ['hermes_wings','Wings of Hermes','armour','leather',3,'Greek','Winged helm and sandals of the messenger god. Faster than any blow.',[['evasion',15],['counter',15]],null,'wind'],
 ['hades_helm','Helm of Darkness','armour','leather',4,'Greek','Hades’ helm of invisibility. Enemies swing at shadows.',[['evasion',22],['counter',35]],['fragile',8],'underworld'],
 ['golden_fleece','The Golden Fleece','armour','leather',4,'Greek','Jason crossed the world for it. It heals every wound and returns from death.',[['regen',4],['evasion',15],['phoenix',30]],['fragile',8],'sun'],
 ['hecate_robes','Robes of Hecate','armour','robe',3,'Greek','Goddess of crossroads. Three torches circle the one who wears her robes.',[['regen',4],['counter',15]],null,'soul'],
 ['merlin_mantle','Mantle of Merlin','armour','robe',3,'Arthurian','Star-woven by the wizard of Camelot. The night sky moves across it.',[['regen',5],['ward',8]],null,'holy'],
 ['prometheus_fire','Fire of Prometheus','armour','robe',4,'Greek','Wrapped in the stolen flame of the gods. It rises from every fall.',[['regen',6],['phoenix',50]],['fragile',10],'fire'],
 ['odin_cloak','Cloak of the Allfather','armour','robe',4,'Norse','Odin’s travelling cloak. Huginn and Muninn, Thought and Memory, fly beside you.',[['regen',6],['ward',12],['phoenix',30]],['clumsy',6],'raven']];

const LEG_ARM = {plate:['thorns',20], leather:['evasion',10], robe:['regen',4]};
const MYTH_ARM = {plate:[['ward',18],['thorns',25]], leather:[['evasion',15],['counter',30]], robe:[['regen',6],['phoenix',40]]};

const TRINKETS = [ // [name, effect, values per rarity]
  ['Ring of Might','STR',[3,5,8,12,16]], ['Swift Feather','AGI',[3,5,8,12,16]], ['Heart Amulet','HPPCT',[6,10,15,22,30]],
  ['Weaponmaster Badge','WPN',[3,5,8,12,16]], ['Ember Charm','BURN',[12,18,25,32,40]], ['Vampire Fang','LIFESTEAL',[4,6,9,12,16]],
  ['Thorn Brooch','THORNS',[8,12,18,25,35]], ['Potion Belt','POTION',[10,20,30,45,60]], ['Scholar’s Quill','QUILL',[1,1,1,2,2]],
  ['Guardian Sigil','GUARD',[10,15,20,28,36]]];
const TRINKET_TEXT = {STR:'+{v} Strength', AGI:'+{v} Agility', HPPCT:'+{v}% max HP', WPN:'+{v} Weapon', BURN:'{v}% chance to burn on hit',
  LIFESTEAL:'Heal {v}% of damage dealt', THORNS:'Reflect {v}% of damage taken', POTION:'Potions heal {v}% more', QUILL:'+{v} extra stat point for every quest you pass',
  GUARD:'Guarding blocks {v}% more damage'};
const CONSUMABLES = {
  hp:      {n:'Health Potion', d:'Heal 35% HP', w:34},
  hp2:     {n:'Greater Potion', d:'Heal 65% HP', w:10},
  str:     {n:'Strength Tonic', d:'+40% damage for 3 turns', w:12},
  iron:    {n:'Iron-Skin Elixir', d:'Take 45% less damage for 3 turns', w:12},
  smoke:   {n:'Smoke Bomb', d:'Dodge the next 2 attacks', w:10},
  fire:    {n:'Firebomb', d:'Deal 60% weapon damage to every enemy and burn them', w:12},
  cleanse: {n:'Cleansing Salts', d:'Remove burn and poison, heal 13%', w:8},
  phoenix: {n:'Phoenix Feather', d:'If you fall this battle, revive at 50% HP (auto)', w:2}};
const ABIL_TEXT = {double:'{v}% chance to strike twice', lifesteal:'Heal {v}% of damage dealt', execute:'+{v}% damage to enemies below 30% HP',
  crit:'{v}% chance to crit (×1.5)', stun:'{v}% chance to stun', burn:'{v}% chance to burn (3% of its max HP a turn for 3 turns)', chain:'Hits jump to a second enemy for {v}%',
  pierce:'Ignores guard and shields', multishot:'Every attack also hits a random second enemy', quake:'{v}% of damage splashes to all enemies',
  thorns:'Reflect {v}% of damage taken', evasion:'+{v}% dodge', regen:'Heal {v}% max HP each turn', ward:'Take {v}% less damage',
  counter:'{v}% chance to counter-attack when hit', phoenix:'Once per battle, revive at {v}% HP',
  maxhp:'DOWNSIDE: −{v}% max HP', fragile:'DOWNSIDE: take {v}% more damage', clumsy:'DOWNSIDE: −{v}% dodge', selfburn:'DOWNSIDE: {v}% chance to burn yourself when attacking',
  slowskill:'DOWNSIDE: Multi and Heavy moves cost {v}0 more energy'};

// Enemy designs: key → [name, art, colour, trait]
const ENEMIES = {
  slime:['Bog Slime','slime','#6fdc4f','split'], goblin:['Goblin Scout','goblin','#7cae3e','swift'], boar:['Tusk Boar','boar','#8a5a3c','brute'], enforcer:['Thought Police','knight','#3b4a63','shield'],
  oBrien:['O’Brien the Inquisitor','inquisitor','#3a3a46','boss'], watcher:['The Watcher','eye','#e9e4da','boss'],
  crab:['Iron Crab','crab','#e0603a','shield'], sprite:['Storm Sprite','wisp','#7fe0e6','burn'], drowned:['Drowned Sailor','ghoul','#5d8a7a','vampiric'], gull:['Storm Gull','bird','#e8e8e8','swift'],
  caliban:['Caliban, Island-Born','brute','#5a7a4a','boss'], prospero:['Prospero, Storm-Caller','mage','#5b3d8f','boss'],
  scarecrow:['Stuffed Scarecrow','scarecrow','#c9a24a','burn'], husk:['Hollow Husk','ghoul','#8c8274','healer'], vulture:['Bone Vulture','bird','#5b4a3a','vampiric'], hound:['Ash Hound','wolf','#6b4b3b','brute'],
  fogcat:['The Yellow Fog Cat','cat','#e6d35a','boss'], shadow:['The Shadow','eye','#2a2433','boss'],
  wolf:['Frost Wolf','wolf','#c8d6e0','swift'], golem:['Ice Golem','golem','#8fc6e8','shield'], owl:['Snow Owl','bird','#f4f4f4','healer'], yeti:['Yeti','yeti','#e8eef2','brute'],
  troll:['Avalanche Troll','brute','#7e9aa8','boss'],
  brawler:['Prole Brawler','goblin','#a0704a','brute'], pwisp:['Propaganda Wisp','wisp','#ff7a5a','burn'], captain:['Thought Police Captain','knight','#22304a','boss'],
  pirate:['Cursed Pirate','ghoul','#4a6a8a','vampiric'], iboar:['Island Boar','boar','#6a4a2a','brute'], arielStorm:['Ariel, Spirit of Storms','wisp','#a0f0ff','boss'],
  sgolem:['Sand Golem','golem','#d9b070','shield'], bandit:['Wasteland Bandit','goblin','#b08a50','swift'], hollowKing:['The Hollow King','scarecrow','#8a6a2a','boss'],
  iwisp:['Frost Wisp','wisp','#cfefff','burn'], sgoblin:['Snow Goblin','goblin','#a8c8d8','swift'], winterOwl:['The Winter Owl','bird','#e8f0ff','boss'], wyrm:['Nightfall Wyrm','wyrm','#3c5a8a','boss']};

// ---- expansion enemies (×3 roster) ----
Object.assign(ENEMIES, {
  rat:['Room 101 Rat','rat','#7a6a6a','swift'], spy:['Junior Spy','goblin','#c04040','swift'], drone:['Ministry Drone','drone','#9aa0a8','burn'], hatemob:['Two Minutes Hate Mob','brute','#8a6a5a','brute'],
  bee:['Golden Country Bee','bat','#ffcf3a','swift'], treant:['Mossy Treant','treant','#5a7a3a','healer'], harpy:['Harpy','harpy','#8a6aa0','swift'], satyr:['Satyr Piper','beastman','#8a6a4a','healer'],
  cyclopsY:['Young Cyclops','cyclops','#9a8a7a','brute'], spider:['Forest Spider','spider','#3a3a2a','vampiric'], bat:['Cave Bat','bat','#4a3a5a','vampiric'], skeleton:['Ruin Skeleton','skeleton','#e8e0d0','shield'],
  minotaur:['Minotaur of the Ministry','beastman','#6a3a2a','boss'], medusa:['Medusa','gorgon','#5a8a5a','boss'], cerberus:['Cerberus','hound3','#3a2a2a','boss'], polyphemus:['Polyphemus','cyclops','#a08a70','boss'],
  colossus:['Big Brother’s Colossus','colossus','#3a3a46','boss'], hydra:['The Lernaean Hydra','hydra','#3a8a5a','boss'],
  jelly:['Storm Jellyfish','jelly','#9fd8ff','burn'], eel:['Lightning Eel','serpent','#4a6a8a','swift'], siren:['Siren','harpy','#4ac0b0','vampiric'], sharkman:['Shark-Raider','beastman','#5a7a9a','brute'],
  barnacle:['Barnacle Golem','golem','#6a8a8a','shield'], ghostsailor:['Ghost-Ship Skeleton','skeleton','#bfe8ff','vampiric'], kelpie:['Kelpie','horse','#2a6a6a','swift'], coralcrab:['Coral Crab','crab','#ff7a6a','shield'],
  stormdjinn:['Storm Djinn','djinn','#6ab0ff','burn'], puffer:['Spiked Pufferfish','puffer','#e8c060','split'], drownknight:['Drowned Knight','knight','#3a6a6a','shield'], seaserpent:['Sea Serpent','serpent','#2a8a8a','brute'],
  scylla:['Scylla','hydra','#4a6a7a','boss'], charybdis:['Charybdis','jelly','#2a4a8a','boss'], sirenqueen:['The Siren Queen','harpy','#2ab0a0','boss'], stephano:['Stephano & Trinculo','brute','#a07a4a','boss'],
  kraken:['The Kraken','kraken','#7a2a4a','boss'], sycorax:['Sycorax the Sea-Witch','mage','#3a5a3a','boss'],
  mummy:['Restless Mummy','mummy','#d8ccb0','shield'], scorpion:['Giant Scorpion','scorpion','#8a4a2a','burn'], jackal:['Jackal Warrior','beastman','#2a2a30','swift'], scarab:['Scarab Swarm','beetle','#1a5a4a','split'],
  sandwurm:['Sand Wurm','serpent','#c8a060','brute'], dustdjinn:['Dust Djinn','djinn','#d8b070','burn'], desertskel:['Bleached Skeleton','skeleton','#f4ead0','swift'], cobra:['Royal Cobra','serpent','#2a4a2a','vampiric'],
  ushabti:['Ushabti Servant','golem','#4a8a9a','shield'], locust:['Locust Swarm','bat','#8a8a3a','swift'], stuffedman:['Stuffed Man','scarecrow','#9a7a4a','healer'], crocman:['Sobek’s Brute','beastman','#4a6a3a','brute'],
  sphinx:['The Sphinx','sphinx','#d8b070','boss'], anubisE:['Anubis, Weigher of Hearts','beastman','#14141a','boss'], magus:['The Weary Magus','mage','#6a4a8a','boss'], setE:['Set, Lord of the Red Desert','beastman','#a02a10','boss'],
  apophis:['Apophis the World-Serpent','serpent','#3a1a4a','boss'], pharaoh:['The Undying Pharaoh','mummy','#ffcf4a','boss'],
  draugr:['Draugr','skeleton','#6a8a9a','vampiric'], icespider:['Ice Spider','spider','#bfe8ff','swift'], frostbat:['Frost Bat','bat','#9fc8e0','swift'], snowfox:['Snow Fox','fox','#f4f4ff','swift'],
  mammoth:['Woolly Mammoth','mammoth','#8a6a4a','brute'], icewraith:['Ice Wraith','djinn','#d8f0ff','vampiric'], raven:['Odin’s Raven','bird','#1a1a22','swift'], polarbear:['Polar Bear','bear','#f4f8ff','brute'],
  giantling:['Frost Giantling','giant','#9fc8e0','brute'], snowserpent:['Snow Serpent','serpent','#e8f4ff','shield'], fallenvalk:['Fallen Valkyrie','harpy','#c8d0e0','shield'], frozentreant:['Frozen Treant','treant','#8ab0c0','healer'],
  skoll:['Sköll, the Sun-Chaser','wolf','#4a4a5a','boss'], hrungnir:['Hrungnir the Stone Giant','giant','#7a8a9a','boss'], hel:['Hel, Queen of the Dead','mage','#3a4a5a','boss'], brynhildr:['Brynhildr the Valkyrie','harpy','#e8e0c0','boss'],
  fenrir:['Fenrir','wolf','#3a3a44','boss'], ymir:['Ymir, First of the Giants','giant','#bfe0f0','boss']});
WORLDS[0].enemies.push('rat','spy','drone','hatemob','bee','treant','harpy','satyr','cyclopsY','spider','bat','skeleton'); WORLDS[0].mini.push('minotaur','medusa','cerberus','polyphemus'); WORLDS[0].bossKeys = ['watcher','colossus','hydra'];
WORLDS[1].enemies.push('jelly','eel','siren','sharkman','barnacle','ghostsailor','kelpie','coralcrab','stormdjinn','puffer','drownknight','seaserpent'); WORLDS[1].mini.push('scylla','charybdis','sirenqueen','stephano'); WORLDS[1].bossKeys = ['prospero','kraken','sycorax'];
WORLDS[2].enemies.push('mummy','scorpion','jackal','scarab','sandwurm','dustdjinn','desertskel','cobra','ushabti','locust','stuffedman','crocman'); WORLDS[2].mini.push('sphinx','anubisE','magus','setE'); WORLDS[2].bossKeys = ['shadow','apophis','pharaoh'];
WORLDS[3].enemies.push('draugr','icespider','frostbat','snowfox','mammoth','icewraith','raven','polarbear','giantling','snowserpent','fallenvalk','frozentreant'); WORLDS[3].mini.push('skoll','hrungnir','hel','brynhildr'); WORLDS[3].bossKeys = ['wyrm','fenrir','ymir'];
// ---- arena-style originals: siege machines, clockwork bombers and bone hordes ----
Object.assign(ENEMIES, {
  bomber:['Clockwork Bomber','bomber','#c8a040','burn'], horde:['Rattlebone Horde','horde','#e8e0d0','split'], hogrider:['Warboar Raider','rider','#7a4a2a','swift'], ironexec:['The Iron Executioner','execut','#5a5f6a','boss'],
  balloon:['Sky-Bomber Balloon','balloon','#c04040','brute'], sparkcart:['Sparkwheel Cart','cart','#4a6a8a','burn'], tideram:['Tidebreaker Ram','ram','#3a6a8a','brute'], brineExec:['The Brine Executioner','execut','#3a6a6a','boss'],
  furnace:['Ember Furnace','furnace','#7a6a5a','burn'], sandhorde:['Sun-Bleached Horde','horde','#f4e4c0','split'], sandram:['Gatebreaker Ram','ram','#a0602a','brute'], sunExec:['The Sun Executioner','execut','#b8902a','boss'],
  frostballoon:['Frost-Bomber Balloon','balloon','#5a8ac0','brute'], frostbomber:['Rime Bomber','bomber','#9fc8e0','burn'], icecart:['Frostspark Cart','cart','#8ab0d0','burn'], frostExec:['The Frost Executioner','execut','#7a9ab8','boss']});
WORLDS[0].enemies.push('bomber','horde','hogrider'); WORLDS[0].mini.push('ironexec');
WORLDS[1].enemies.push('balloon','sparkcart','tideram'); WORLDS[1].mini.push('brineExec');
WORLDS[2].enemies.push('furnace','sandhorde','sandram'); WORLDS[2].mini.push('sunExec');
WORLDS[3].enemies.push('frostballoon','frostbomber','icecart'); WORLDS[3].mini.push('frostExec');
// ---- ★★★★★★ myth-god dungeons: one god per fight, two per land ----
Object.assign(ENEMIES, {
  zeusGod:['Zeus, King of Olympus','god','#f4f0e6','boss'], aresGod:['Ares, God of War','god','#8a1a1a','boss'],
  poseidonGod:['Poseidon, Lord of the Sea','god','#2a8a8a','boss'], susanooGod:['Susanoo, the Storm God','god','#3a3a5a','boss'],
  raGod:['Ra, the Sun God','god','#e8b030','boss'], sekhmetGod:['Sekhmet, the Lioness','god','#a8402a','boss'],
  odinGod:['Odin, the All-Father','god','#4a5a7a','boss'], thorGod:['Thor, the Thunderer','god','#5a6a8a','boss']});
WORLDS[0].gods = ['zeusGod','aresGod']; WORLDS[1].gods = ['poseidonGod','susanooGod']; WORLDS[2].gods = ['raGod','sekhmetGod']; WORLDS[3].gods = ['odinGod','thorGod'];
// ---- one signature move per Legendary / Mythical weapon, drawn from its myth (no two weapons share one) ----
// ops: hit(mult,opts) all(mult,opts) multi(n,mult,opts) heal(scope,pct) revive(pct) rally(amt,rounds) aegis(amt,rounds) weak(rounds,scope) vuln(rounds,scope,amt)
//      stun(chance,scope) burn(scope) cleanse() energy(n) steal(pct) selfhurt(pct) smoke(n,scope) shield(rounds) judge(pct) gentle() double(chance)
const SIGS = {
  zeus_gauntlets:['Olympian Uppercut','A thunder-charged uppercut (180%) with a 50% chance to stun',[['hit',1.8,{stun:50}]]],
  heracles_cestus:['Twelve Labours','Six relentless blows (40% each) spread across the foes',[['multi',6,0.4]]],
  zeus_bolt:['Wrath of Olympus','The sky splits: 110% to every enemy, 30% chance to stun each',[['all',1.1],['stun',30,'all']]],
  prometheus_hands:['Stolen Fire','80% fire to every enemy, sets them burning, and the gift of fire gives the party +25 energy',[['all',0.8],['burn','all'],['energy',25]]],
  harpe:['Medusa’s Bane','A beheading stroke (160%); the Gorgon’s gaze petrifies (70% stun)',[['hit',1.6,{stun:70}]]],
  excalibur:['Lady of the Lake','The lake’s blessing heals the party 20% and washes away burns and frost',[['heal','party',0.2],['cleanse']]],
  ares_sword:['Bloodlust of Ares','A savage cut (150%) that drives the party into a war-frenzy: +25% damage for 2 rounds',[['hit',1.5],['rally',0.25,2]]],
  gram:['Fafnir’s End','The dragon-slayer’s thrust (200%); triple damage against a foe below 35% HP',[['hit',2.0,{exec:2}]]],
  achilles_spear:['Heel Strike','A piercing thrust (130%) at the weak spot: the target takes 40% more damage for 3 rounds',[['hit',1.3,{pierce:true}],['vuln',3,'one',0.4]]],
  gae_bolg:['Thirty Barbs','The barbed spear (120%) opens wounds: it bleeds and takes 25% more damage for 2 rounds',[['hit',1.2],['burn','one'],['vuln',2,'one',0.25]]],
  poseidon_trident:['Earthshaker','The ground heaves: 100% to every enemy and all of them deal 30% less for 2 rounds',[['all',1.0],['weak',2,'all']]],
  gungnir:['Never Misses','Odin’s spear always finds its mark: a piercing 240% guaranteed critical',[['hit',1.2,{pierce:true,crit:true}]]],
  artemis_bow:['Moonlit Hunt','Four silver arrows (55% each) at the hunted',[['multi',4,0.55]]],
  odysseus_bow:['Through Twelve Axes','One arrow through every enemy in a line: 120% to the target, 50% to all others',[['hit',1.2,{pierce:true}],['others',0.5]]],
  apollo_bow:['Plague Arrows','Arrows of sickness: 70% to every enemy and they deal 30% less for 3 rounds',[['all',0.7],['weak',3,'all']]],
  gandiva:['Pashupatastra','The divine weapon: 140% to every enemy',[['all',1.4]]],
  dragon_scroll:['Dragon’s Breath','A dragon of ink and flame: 90% to every enemy and sets them burning',[['all',0.9],['burn','all']]],
  heracles_club:['Nemean Smash','A crushing blow (170%); the lion pelt hardens you (take 45% less for 2 turns)',[['hit',1.7],['shield',2]]],
  hephaestus_hammer:['Forge of the Gods','Reforge the party’s armour: they take 30% less damage for 2 rounds and gain 15 energy',[['aegis',0.3,2],['energy',15]]],
  mjolnir:['Thunder Return','The hammer strikes (130%), flies through every foe (60%) and returns; 25% stun each',[['hit',1.3],['others',0.6],['stun',25,'all']]],
  dagda_club:['Life and Death','One end kills, one end heals: a 160% blow, then the party heals 15%',[['hit',1.6],['heal','party',0.15]]],
  kronos_sickle:['Devour the Hours','Time stops: each enemy has a 45% chance to lose its turn',[['stun',45,'all']]],
  morrigan_scythe:['Battle-Crow’s Omen','Doom is foretold: every enemy deals 30% less (3 rounds) and takes 20% more (2 rounds)',[['weak',3,'all'],['vuln',2,'all',0.2]]],
  thanatos_scythe:['Gentle Death','Below 35% HP an ordinary foe simply dies (bosses take 300%); otherwise a 100% cut',[['gentle']]],
  hades_reaper:['Helm of Darkness','A reaping cut (110%), then the party turns invisible: everyone dodges the next attack',[['hit',1.1],['smoke',1,'party']]],
  sekhmet_claws:['Lioness Pounce','Three raking strikes (70% each); drink 30% of the damage as health',[['multi',3,0.7],['steal',0.3]]],
  tyr_gauntlet:['Binding of Fenrir','Týr’s sacrifice binds the beast: the target is stunned and deals 30% less for 2 rounds',[['stun',100,'one'],['weak',2,'one']]],
  raijin_fists:['Thunder Drums','90% lightning to every enemy, 35% stun each, and the party gains 10 energy',[['all',0.9],['stun',35,'all'],['energy',10]]],
  hanuman_fists:['Sanjeevani Mountain','Hanuman carries the healing mountain: revive a fallen ally at 40%, and the party heals 15%',[['revive',0.4],['heal','party',0.15]]],
  khopesh_ra:['Eye of Ra','A sun-blade cut (150%) that burns and leaves the target taking 25% more for 2 rounds',[['hit',1.5],['burn','one'],['vuln',2,'one',0.25]]],
  claiomh_solais:['Sword of Light','Blinding light: 90% to every enemy, then the party heals 10% and is cleansed',[['all',0.9],['heal','party',0.1],['cleanse']]],
  tyrfing:['Three Evil Wishes','A cursed 280% blow; the curse costs you 10% of your HP',[['hit',2.8],['selfhurt',0.1]]],
  durendal:['Roland’s Last Stand','A 140% stroke; double damage while you are below 40% HP',[['hit',1.4,{low:2}]]],
  zulfiqar:['Twin-Pointed Cleave','The two-pointed blade strikes two different foes for 100% each',[['multi',2,1.0,{spread:true}]]],
  wyrmbane_slab:['Dragonslayer’s Swing','The iron slab hits every enemy for 130% with a 20% chance to stagger each',[['all',1.3],['stun',20,'all']]],
  kusanagi:['Grass-Cutter Gale','The wind obeys the blade: 100% to every enemy, who deal 30% less next round',[['all',1.0],['weak',1,'all']]],
  masamune:['Leaf on the Stream','The peaceful sword (120%) spares you: heal 20% of your HP',[['hit',1.2],['heal','self',0.2]]],
  muramasa:['Bloodthirst','The hungry blade bites (200%) and drinks half the damage as health',[['hit',2.0],['steal',0.5]]],
  habakiri:['Orochi Slayer','Eight strikes for the eight-headed serpent (30% each)',[['multi',8,0.3]]],
  moonlit_odachi:['Crescent Moon Arc','A moon-shaped arc: 120% to every enemy, who take 20% more next round',[['all',1.2],['vuln',1,'all',0.2]]],
  ronin_blade:['Iaido Draw','One lightning draw: a piercing 190% with +50% crit chance',[['hit',1.9,{pierce:true,critBonus:0.5}]]],
  spear_of_lugh:['Spear of Victory','The fiery spear (150%) burns the target and lifts the party: +15% damage for 3 rounds',[['hit',1.5],['burn','one'],['rally',0.15,3]]],
  tomoe_naginata:['Sweeping Guard','A wide sweep (80% to all) that ends in a guard: the party takes 20% less next round',[['all',0.8],['aegis',0.2,1]]],
  ruyi_staff:['Monkey King’s Clones','Clones leap from a hair: five strikes (45% each) at random foes',[['multi',5,0.45]]],
  trishula:['Three Worlds Pierce','The trident pierces three foes for 90% each',[['multi',3,0.9,{spread:true,pierce:true}]]],
  athena_spear:['Aegis of Athena','Wisdom’s shield: the party takes 35% less for 2 rounds and the target deals 30% less',[['aegis',0.35,2],['weak',2,'one']]],
  wadjet_spear:['Cobra’s Venom','A venomous thrust (110%): poisoned and weakened for 2 rounds',[['hit',1.1],['burn','one'],['weak',2,'one']]],
  neith_bow:['Weaver’s Net','A net of arrows: every enemy deals 30% less for 2 rounds and the target may be caught (50% stun)',[['weak',2,'all'],['stun',50,'one']]],
  hachiman_yumi:['Divine Wind Arrow','A war-god’s arrow (150%) that fills the party with 20 energy',[['hit',1.5],['energy',20]]],
  pinaka:['Fall of Tripura','Shiva’s bow burns the three cities: 160% to every enemy',[['all',1.6]]],
  skadi_bow:['Winter Hunt','Three frost arrows (60% each); the target freezes (40% stun)',[['multi',3,0.6],['stun',40,'one']]],
  perun_axe:['Perun’s Strike','The thunder-axe (160%) with a 40% stun, and sparks hit every other foe (30%)',[['hit',1.6,{stun:40}],['others',0.3]]],
  set_maul:['Chaos Storm','A red desert storm: 100% to every enemy, who deal 30% less for 2 rounds',[['all',1.0],['weak',2,'all'],['burn','one']]],
  oni_kanabo:['Oni Rampage','A brutal 220% blow with a 25% chance to swing again',[['hit',2.2],['double',25]]],
  gogmagog_hammer:['Giant’s Footfall','The earth shakes: 80% to every enemy, 25% stun each',[['all',0.8],['stun',25,'all']]],
  sharur:['Smasher of Thousands','120% to every enemy; double damage on any below 35% HP',[['all',1.2,{exec:1}]]],
  surtr_sword:['Ragnarök Flame','The fire-giant’s blade: 130% to every enemy and sets them all burning',[['all',1.3],['burn','all']]],
  anubis_scythe:['Weighing of the Heart','Judges the target: damage equal to 25% of its current HP (8% of max for bosses), and you heal 15%',[['judge',0.25],['heal','self',0.15]]],
  hel_scythe:['Realm of the Dead','Hel’s cold: 80% to every enemy, and you drain 25% of it as health',[['all',0.8],['steal',0.25]]],
  shinigami_scythe:['Death Note','The target’s name is written: it takes 50% more damage for 3 rounds',[['vuln',3,'one',0.5]]],
  morana_scythe:['Winter’s Death','Killing frost: 70% to every enemy, 30% chance to freeze each',[['all',0.7],['stun',30,'all']]],
  crook_osiris:['Rebirth of Osiris','Revive a fallen ally at 50% (if none have fallen, the party heals 15%)',[['revive',0.5]]],
  ankh_isis:['Breath of Life','The ankh breathes life: the party heals 30% and is cleansed',[['heal','party',0.3],['cleanse']]],
  caduceus:['Messenger’s Haste','Hermes’ speed: the party gains 35 energy and +10% damage for 2 rounds',[['energy',35],['rally',0.1,2]]],
  merlin_staff:['Arthur’s Counsel','Merlin’s plan: the party deals +20% (3 rounds) and takes 15% less (2 rounds)',[['rally',0.2,3],['aegis',0.15,2]]],
  gambanteinn:['Seiðr Curse','A wand-curse: every enemy deals 30% less (3 rounds) and takes 30% more (2 rounds)',[['weak',3,'all'],['vuln',2,'all',0.3]]],
  thyrsus:['Bacchic Frenzy','Wild revels: the party deals +30% damage for 2 rounds and heals 5%',[['rally',0.3,2],['heal','party',0.05]]],
  asclepius_rod:['Raise the Fallen','The healer’s rod: revive a fallen ally at 40% and heal the party 10%',[['revive',0.4],['heal','party',0.1]]],
  ra_staff:['Solar Barque','The sun sails across the battlefield: 120% to every enemy, burns them, and heals the party 10%',[['all',1.2],['burn','all'],['heal','party',0.1]]],
  moon_princess_staff:['Moonlight Healing','Healing moonlight: the party heals 22% and takes 20% less next round',[['heal','party',0.22],['aegis',0.2,1]]],
  sudarshana:['Wheel of Time','The spinning discus bounces six times (50% each) through the foes',[['multi',6,0.5,{spread:true}]]],
  fujin_fan:['Wind-Bag Gale','Fūjin opens his wind-bag: 80% to every enemy, they deal 30% less, and the party dodges the next attack',[['all',0.8],['weak',1,'all'],['smoke',1,'party']]],
  apollo_discus:['Hyacinth’s Discus','The fateful discus (170%) with a 40% stun',[['hit',1.7,{stun:40}]]],
  night_shuriken:['Silent Night','Five silent stars (45% each), then you vanish: dodge the next 2 attacks',[['multi',5,0.45],['smoke',2,'self']]],
  tomoe_fan:['Iron Gale','A gale of iron: 90% to every enemy and the party takes 15% less next round',[['all',0.9],['aegis',0.15,1]]],
  khonsu_disc:['Phases of the Moon','A waxing strike (120%), then the moon restores you: heal 15% and gain 20 energy',[['hit',1.2],['heal','self',0.15],['energy',20,'self']]],
  durga_chakram:['Mahishasura’s End','The demon-slayer’s chakram: 160%, and 50% more against bosses',[['hit',1.6,{boss:1.5}]]],
  brisingamen_knuckles:['Freyja’s Allure','The necklace enchants: every enemy deals 30% less for 2 rounds and you heal 15%',[['weak',2,'all'],['heal','self',0.15]]],
  murasame:['Rain Blade','The blade drips rain: 70% to every enemy, then the party is cleansed and heals 8%',[['all',0.7],['cleanse'],['heal','party',0.08]]],
  atomic:['I Am Atomic','The final technique: 250% to every enemy and a 50% chance to stun each',[['all',2.5],['stun',50,'all']]]};
// ---- Pokémon-style move sets ----
// Type 1 (energy saver) for Mythical weapons: a unique basic move with a small mythic rider.
const MYTHT1 = {zeus_bolt:['Static Jab','burn'], prometheus_hands:['Ember Palm','burn'], ares_sword:['War-God’s Cut','crit'], gram:['Dragon-Scale Edge','pierce'], poseidon_trident:['Riptide Thrust','slow'],
  gungnir:['Rune-Spear Jab','crit'], apollo_bow:['Sunlit Shot','blind'], gandiva:['Divine String','energy'], dragon_scroll:['Ink Dragon Flick','burn'], mjolnir:['Thunder Tap','stun'], dagda_club:['Cauldron Knock','steal'],
  thanatos_scythe:['Last Breath','poison'], hades_reaper:['Shade Slash','blind'], raijin_fists:['Drumbeat Jab','stun'], hanuman_fists:['Monkey Fist','energy'], claiomh_solais:['Gleaming Cut','blind'],
  tyrfing:['Cursed Nick','poison'], wyrmbane_slab:['Slab Bash','stun'], muramasa:['Hungry Edge','steal'], habakiri:['Serpent Fang','poison'], moonlit_odachi:['Moonbeam Cut','slow'], spear_of_lugh:['Sunfire Jab','burn'],
  ruyi_staff:['Growing Staff','pierce'], trishula:['Third-Eye Thrust','burn'], pinaka:['Shiva’s Arrow','pierce'], skadi_bow:['Rime Shot','slow'], set_maul:['Red Desert Blow','blind'], sharur:['Talking Mace','crit'],
  surtr_sword:['Muspel Slash','burn'], anubis_scythe:['Jackal Reap','poison'], hel_scythe:['Grave-Cold Cut','slow'], ankh_isis:['Life-Spark','steal'], gambanteinn:['Wand-Lash','blind'], ra_staff:['Sun-Ray','burn'],
  moon_princess_staff:['Crescent Spark','energy'], sudarshana:['Spinning Rim','chain'], fujin_fan:['Gust Slap','slow'], atomic:['Slime Slice','chain']};
// Type 4 accuracy, extra power and the DOWNSIDE that comes with Mythical power. down ops: selfhurt(pct) teamhurt(pct) recharge exhaust selfstatus(name,turns)
const SIGX = {
  zeus_bolt:{acc:85, down:[['teamhurt',0.05]], note:'Lightning arcs back through the party (5% HP each)'},
  prometheus_hands:{acc:100, down:[['selfstatus','burn',2]], note:'You burn too'},
  ares_sword:{acc:90, down:[['selfstatus','vuln',2]], note:'Reckless: you take 25% more damage for 2 rounds'},
  gram:{acc:90, down:[], note:''},
  poseidon_trident:{acc:85, down:[['exhaust']], note:'Leaves you with no energy'},
  gungnir:{acc:100, down:[['recharge']], note:'Must recall the spear: you lose your next turn'},
  apollo_bow:{acc:85, down:[['selfstatus','blind',1]], note:'The sun dazzles you too'},
  gandiva:{acc:80, down:[['selfhurt',0.08]], note:'Drawing the divine bow costs 8% HP'},
  dragon_scroll:{acc:85, down:[['teamhurt',0.04]], note:'Dragon fire singes the party'},
  mjolnir:{acc:90, down:[['exhaust']], note:'Throwing the hammer drains all your energy'},
  dagda_club:{acc:95, down:[], note:''},
  thanatos_scythe:{acc:80, down:[['selfstatus','slow',2]], note:'Death’s weight slows you'},
  hades_reaper:{acc:95, down:[], note:''},
  raijin_fists:{acc:85, down:[['selfhurt',0.05]], note:'The drums shock you too'},
  hanuman_fists:{acc:100, down:[['recharge']], note:'Carrying the mountain: you lose your next turn'},
  claiomh_solais:{acc:90, down:[], note:''},
  tyrfing:{acc:75, down:[], note:'(curse built in)'},
  wyrmbane_slab:{acc:80, down:[['selfstatus','slow',1]], note:'Heavy: you are slowed'},
  muramasa:{acc:90, down:[['teamhurt',0.06]], note:'The blade thirsts for allies’ blood too'},
  habakiri:{acc:85, down:[['exhaust']], note:'Eight strikes leave you spent'},
  moonlit_odachi:{acc:85, down:[], note:''},
  spear_of_lugh:{acc:90, down:[['selfstatus','burn',1]], note:'The spear’s fire licks your hands'},
  ruyi_staff:{acc:85, down:[], note:''},
  trishula:{acc:90, down:[['recharge']], note:'Shiva’s weapon needs a turn to return'},
  pinaka:{acc:75, down:[['recharge']], note:'Firing Pinaka costs you your next turn'},
  skadi_bow:{acc:90, down:[['selfstatus','slow',1]], note:'Numb with cold'},
  set_maul:{acc:75, down:[['teamhurt',0.05]], note:'Chaos hits friend and foe'},
  sharur:{acc:85, down:[['selfhurt',0.06]], note:'The mace demands blood'},
  surtr_sword:{acc:80, down:[['teamhurt',0.06]], note:'Ragnarök fire spares no one'},
  anubis_scythe:{acc:100, down:[], note:''},
  hel_scythe:{acc:90, down:[['selfstatus','vuln',2]], note:'Half your body turns to death: take 25% more'},
  ankh_isis:{acc:100, down:[['exhaust']], note:'Giving life drains your energy'},
  gambanteinn:{acc:80, down:[], note:''},
  ra_staff:{acc:85, down:[['selfhurt',0.06]], note:'The sun scorches its bearer'},
  moon_princess_staff:{acc:100, down:[], note:''},
  sudarshana:{acc:90, down:[], note:''},
  fujin_fan:{acc:85, down:[['selfstatus','blind',1]], note:'Dust in your eyes'},
  atomic:{acc:70, down:[['recharge'],['exhaust']], note:'So powerful it costs your next turn and all your energy'}};
// Types 2-4 for Common / Rare / Epic weapons (shared by weapon type)
const ARCHMOVES = {
  fist:   {t2:['Flurry','multi',3,0.45,90], t3:['Haymaker',40,90,2.0,{stun:20}], t4:['Pressure Point','A precise jab (120%) that blinds the target for 2 turns',[['hit',1.2],['status','blind',100,'one',2]],90]},
  blade:  {t2:['Cleave','area',0,0.65,85], t3:['Heavy Slash',45,92,2.1,{}], t4:['Blade Dance','Three whirling cuts (60% each) and you become Swift for 2 rounds',[['multi',3,0.6],['buff','swift',2,'self']],90]},
  pole:   {t2:['Sweep','area',0,0.6,85], t3:['Impale',45,93,2.1,{pierce:true}], t4:['Phalanx','Locked spears: the party takes 20% less damage for 2 rounds',[['aegis',0.2,2]],100]},
  ranged: {t2:['Volley','multi',4,0.38,90], t3:['Aimed Shot',45,95,2.0,{critBonus:0.25}], t4:['Poison Arrow','An arrow (100%) that poisons for 4 turns',[['hit',1.0],['status','poison',100,'one',4]],95]},
  heavy:  {t2:['Shockwave','area',0,0.55,85,{stun:15}], t3:['Crushing Blow',60,90,2.8,{}], t4:['Earthquake','80% to every enemy and slows them for 2 rounds',[['all',0.8],['status','slow',100,'all',2]],80]},
  scythe: {t2:['Reap','area',0,0.55,85,{steal:0.3}], t3:['Execution',50,92,2.0,{exec:1}], t4:['Soul Harvest','60% to every enemy, then heal 20%',[['all',0.6],['heal','self',0.2]],85]},
  katana: {t2:['Thousand Cuts','multi',4,0.4,90], t3:['Iaido',40,95,1.9,{critBonus:0.35}], t4:['Focus Strike','Meditate: you become Empowered (+25% damage) and Enlightened (+15 energy a turn) for 2 rounds',[['buff','empower',2,'self'],['buff','enlight',2,'self']],100]},
  staff:  {t2:['Arcane Storm','area',0,0.55,85,{burn:20}], t3:['Arcane Lance',50,95,2.2,{}], t4:['Frost Nova','50% to every enemy with a 30% chance to freeze each',[['all',0.5],['status','freeze',30,'all',1]],85]},
  thrown: {t2:['Ricochet','multi',5,0.33,90,{spread:true}], t3:['Pinning Throw',40,93,1.8,{slow:2}], t4:['Smoke Bomb','A toss (80%) and a cloud of smoke: the party dodges the next attack',[['hit',0.8],['smoke',1,'party']],100]}};
const BASICMOVE = {fist:'Jab', blade:'Slash', pole:'Thrust', ranged:'Quick Shot', heavy:'Bash', scythe:'Reap Strike', katana:'Draw Cut', staff:'Arcane Bolt', thrown:'Toss'};
const STATUS_TEXT = {burn:'Burning: loses 4% HP a turn', poison:'Poisoned: loses 5% HP a turn', freeze:'Frozen: loses its next turn', blind:'Blinded: −20% accuracy', slow:'Slowed: easier to hit, acts last',
  weak:'Weakened: deals 30% less', vuln:'Exposed: takes more damage', empower:'Empowered: +25% damage', swift:'Swift: +10% accuracy and dodge', enlight:'Enlightened: +15 energy a turn, +15% crit', god:'Godhood: +50% damage, immune to statuses', recharge:'Recharging: loses its next turn'};
const TRAITS = {
  swift:'Swift: fast, strikes twice', brute:'Brute: winds up charged attacks', shield:'Shielded: often guards (halves damage)',
  burn:'Blazing: its attacks can burn you', vampiric:'Vampiric: heals from damage it deals', healer:'Healer: heals itself or allies', split:'Gooey: regenerates a little each turn',
  boss:'Boss: enrages at 50% HP'};
const GOD_TEXT = {zeusGod:'Hurls thunderbolts from a clear sky', aresGod:'Spear and shield: hits hardest when cornered', poseidonGod:'Summons crashing tidal waves', susanooGod:'Storm-blade slashes come in threes', raGod:'A beam of the noon sun', sekhmetGod:'Fire-breath and a hunter’s pounce', odinGod:'Gungnir never misses; his ravens watch', thorGod:'Mjölnir shakes the ground'};

// HSC-style LTQ questions (written in the style of recent papers, not copied)
const LTQ = {
 common:['How does your prescribed text represent the tension between individual desires and collective pressures?',
   'Explore how your prescribed text challenges assumptions about the resilience of the human spirit.',
   '“Human experiences are shaped by fear as much as by hope.” To what extent does your prescribed text support this view?',
   'How does storytelling in your prescribed text illuminate the paradoxes of human behaviour?',
   'Evaluate how your prescribed text represents the cost of conformity.',
   'In what ways does your prescribed text invite responders to reflect on the fragility of truth?',
   '“Texts reveal the anomalies and inconsistencies that make us human.” How does your prescribed text do this?',
   'How does your prescribed text explore the relationship between love, loyalty and survival?',
   'Explain how your prescribed text represents the limits of human endurance.',
   'To what extent does your prescribed text suggest that isolation shapes identity?'],
 moda:['How does the conversation between your texts reshape our understanding of power and forgiveness?',
   'Evaluate how Atwood’s reimagining challenges the values of The Tempest.',
   'To what extent does Hag-Seed resolve the tensions left open in The Tempest?',
   '“A later text both honours and interrogates its source.” Discuss with reference to your prescribed texts.',
   'How do your prescribed texts use the idea of performance to explore freedom?',
   'In what ways does Hag-Seed give voice to those marginalised in The Tempest?',
   'How does the textual conversation between your texts illuminate changing ideas about justice?',
   'Explore how artistry in your prescribed texts shapes their treatment of revenge.',
   'To what extent does context shape the way your prescribed texts represent authority?',
   'How do your prescribed texts explore the transformative power of art?'],
 modb:['How does Eliot’s poetry explore the search for meaning in a fragmented world?',
   'Evaluate how Eliot’s use of form shapes your understanding of spiritual desolation.',
   '“Eliot’s poetry is defined by paralysis rather than hope.” To what extent do you agree?',
   'How does your personal response to Eliot’s poetry reflect its textual integrity?',
   'Explore how Eliot represents the cost of transformation.',
   'In what ways does Eliot’s poetry remain relevant to contemporary audiences?',
   'How does Eliot’s poetry represent the tension between belief and doubt?',
   'Evaluate the significance of the individual voice in Eliot’s poetry.',
   'How does Eliot use imagery to explore modern alienation?',
   'To what extent is Eliot’s poetry a portrait of a collective rather than a personal crisis?'],
 modc:['Explain how your imaginative piece shows the influence of a prescribed text on your craft.',
   'How did you use structure to shape your reader’s response to guilt and forgiveness?',
   'Evaluate how your choice of narrative voice conveys the complexity of memory.',
   'How have you used motif to convey an idea about identity?',
   'Explain how your piece explores the power of language to include or exclude.',
   'How does your imaginative piece use time to deepen its meaning?',
   'Evaluate how symbolism in your piece reflects your reading of Harwood.',
   'How have you crafted your ending to resonate with your reader?',
   'Explain how your piece represents an ordinary moment with moral weight.',
   'How does your piece use dialogue to reveal character?']};
const BOONS = [ // id, name, slots, cost (Wisdom), text
  ['trained','Trained',1,40,'+2 to every stat'], ['bulk','Bulk Up',1,50,'+10% max HP'], ['quick','Quick Hands',1,50,'Start every fight with +30 energy'],
  ['rested','Well Rested',1,60,'Resting at camp heals 50% instead of 30%'], ['potion','Potion Master',1,60,'Potions heal 20% more'], ['focusmind','Focused Mind',1,70,'Focus gives +65 energy instead of +45'],
  ['first','First Strike',1,80,'You always act before enemies, however fast they are'], ['thorn','Thorned Hide',1,80,'Reflect 12% of damage taken'], ['adrenaline','Adrenaline Surge',1,90,'+25% damage while below 35% HP'],
  ['second','Second Wind',1,100,'Start each fight below 50% HP? Heal 20% first'], ['vamp','Vampiric Bloodline',2,120,'Heal 5% of all damage you deal'], ['dance','Death’s Dance',2,130,'+8% dodge'],
  ['iron','Iron Hide',2,140,'Take 10% less damage'], ['exec','Executioner',2,150,'+35% damage to enemies below 30% HP'], ['hunter','Treasure Hunter',2,160,'+1 item in every chest'],
  ['lucky','Lucky Find',2,170,'Rarer gear drops more often'], ['berserk','Berserker',2,180,'+20% damage but −10% max HP'], ['will','Force of Will',2,200,'Once per fight, survive a fatal hit at 1 HP'],
  ['scholar','Scholar',3,240,'+1 extra stat point for every Hard quest you pass'], ['sage','Sage of the Codex',3,260,'Passing every quest at a camp also heals you to full']];
const EVENTS = {
  river:{n:'Mystic River', d:'Clear water glitters between the stones.', opts:[['Drink deeply','Heal 60% HP'],['Fill your flasks','Gain 2 Health Potions']]},
  campsite:{n:'Abandoned Campsite', d:'Someone left in a hurry.', opts:[['Search the packs','Find 2 random items'],['Rest by the old fire','Heal 35% HP and +15 Ink']]},
  altar:{n:'Strange Altar', d:'An altar hums with old power. It wants something from you.', opts:[['Offer blood','Lose 25% current HP, gain 4 stat points'],['Walk away','Nothing happens']]},
  aura:{n:'Strange Aura', d:'A shimmering presence blocks the path. It looks dangerous, and its hoard glitters.', opts:[['Fight it','A ★★★★ elite fight with a richer chest'],['Sneak around','Nothing happens']]},
  shrine:{n:'Scholar’s Shrine', d:'Pages flutter around a stone lectern.', opts:[['Study here','Take one Hard quest now for +5 bonus points'],['Pray','+20 Wisdom']]},
  merchant:{n:'Wandering Merchant', d:'“Rare wares, fair prices!”', opts:[['Browse','Open the shop at half price'],['Trade gossip','+25 Ink']]}};
const SHOP = {hp:30, hp2:50, str:35, iron:35, smoke:30, fire:40, cleanse:20, phoenix:150};
// ---- expansion: Egyptian, Norse, Japanese, Chinese, Hindu, Celtic, Slavic, Mesopotamian relics + original anime-style pieces ----
const LEGENDS2 = [
 // fist
 ['sekhmet_claws','Claws of Sekhmet','weapon','fist',3,'Egyptian','The lioness goddess of war. Her claws hunger after the first wound.',[['double',30],['lifesteal',12]],null,'blood',{b:'gaunt',claws:1,metal:0xd8a040,edge:0xfff0c0,accent:0x1a6aa0,rune:0xffc040}],
 ['tyr_gauntlet','Gauntlet of Týr','weapon','fist',3,'Norse','Týr gave his hand to bind Fenrir. This iron gauntlet replaced it.',[['stun',25],['double',20]],null,'rune',{b:'gaunt',metal:0x8a96a8,edge:0xe8f6ff,accent:0x5a3a20,rune:0x6fd0ff}],
 ['raijin_fists','Fists of Raijin','weapon','fist',4,'Japanese','The thunder god drums the sky. Every punch is a thunderclap.',[['chain',55],['double',35]],['fragile',10],'thunder',{b:'gaunt',metal:0x2a3a8a,edge:0xfff080,accent:0xc02020,rune:0xfff080,flame:0x9fd8ff}],
 ['hanuman_fists','Fists of Hanuman','weapon','fist',4,'Hindu','The monkey god who leapt the ocean. His blows split mountains.',[['quake',35],['double',30],['stun',15]],['clumsy',6],'sun',{b:'gaunt',metal:0xd86a20,edge:0xffe080,accent:0xffcf4a,rune:0xffa020,flame:0xff9020}],
 // blade
 ['khopesh_ra','Khopesh of Ra','weapon','blade',3,'Egyptian','The sun god’s hooked sword. It burns like noon on the Nile.',[['burn',30],['crit',15]],null,'sun',{b:'sword',L:1.6,wd:0.3,curve:1,guard:'none',metal:0xffcf4a,edge:0xfff6d0,accent:0x1a6aa0,rune:0xffd040}],
 ['claiomh_solais','Claíomh Solais','weapon','blade',4,'Irish','The Sword of Light of Nuada. No enemy escapes its glare.',[['crit',35],['chain',40],['lifesteal',15]],['maxhp',10],'holy',{b:'sword',L:2.8,wd:0.26,guard:'wing',metal:0xf0f8ff,edge:0xffffff,accent:0x30c0a0,rune:0xfff6b0,flame:0xfff0a0}],
 ['tyrfing','Tyrfing, the Cursed Blade','weapon','blade',4,'Norse','It never misses and never rusts, but it must take a life each time it is drawn.',[['crit',40],['execute',70]],['selfburn',8],'blood',{b:'sword',L:2.6,wd:0.27,guard:'cross',metal:0x3a3040,edge:0xff5050,accent:0xffcf4a,rune:0xff3030,flame:0xff3030}],
 ['durendal','Durendal','weapon','blade',3,'French','Roland’s unbreakable sword, said to hold a saint’s tooth in its golden hilt.',[['lifesteal',12],['stun',15]],null,'holy',{b:'sword',L:2.6,wd:0.25,guard:'cross',metal:0xe0e6ee,edge:0xffffff,accent:0xffcf4a,rune:0xffe080}],
 ['zulfiqar','Zulfiqar','weapon','blade',3,'Arabian','The legendary forked sword: two points, one strike.',[['double',30],['crit',15]],null,'bronze',{b:'sword',L:2.5,wd:0.32,guard:'cross',fork:1,metal:0xd8dde3,edge:0xffffff,accent:0x2a8a5a,rune:0x60e0a0}],
 ['wyrmbane_slab','Wyrmbane, the Iron Slab','weapon','blade',4,'Original (anime style)','Too big to be called a sword. Too heavy, too thick, too rough. It was made to kill dragons.',[['quake',45],['stun',25],['execute',40]],['clumsy',8],'blood',{b:'sword',L:3.6,wd:0.7,guard:'none',slab:1,metal:0x3a3a40,edge:0x6a6a70,accent:0x2a1a10,rune:0xff3020}],
 // katana (new archetype)
 ['kusanagi','Kusanagi-no-Tsurugi','weapon','katana',3,'Japanese','Pulled from the tail of the eight-headed serpent. It cuts the wind itself.',[['crit',30],['double',20]],null,'wind',{b:'katana',L:2.6,metal:0xe8eef6,edge:0xffffff,tsuba:0xffcf4a,wrap:0x1a2a6a,rune:0x9fe8ff}],
 ['masamune','Masamune','weapon','katana',3,'Japanese','The calm blade. Leaves float around it untouched; only the wicked are cut.',[['crit',25],['lifesteal',12]],null,'holy',{b:'katana',L:2.7,metal:0xf4f8ff,edge:0xffffff,tsuba:0xc0c8d0,wrap:0xf4f4f4,rune:0xd8f0ff}],
 ['muramasa','Muramasa','weapon','katana',4,'Japanese','The hungry blade. Once drawn, it will not be sheathed without blood.',[['crit',45],['lifesteal',25],['double',20]],['selfburn',8],'blood',{b:'katana',L:2.8,metal:0x6a1018,edge:0xff4050,tsuba:0x1a1a1a,wrap:0x8a0a1a,rune:0xff2a3a,flame:0xff2030}],
 ['habakiri','Ame-no-Habakiri','weapon','katana',4,'Japanese','Susanoo’s sword that slew the great serpent Orochi. Storms follow its edge.',[['chain',50],['crit',35]],['fragile',10],'thunder',{b:'katana',L:2.9,metal:0x9fb8d8,edge:0xffffff,tsuba:0x2a3a8a,wrap:0x2a2a50,rune:0xbfe8ff,flame:0x9fd8ff}],
 ['moonlit_odachi','Moonlit Ōdachi','weapon','katana',4,'Original (anime style)','A blade as long as its wielder is tall. Under the moon it leaves crescents of light.',[['crit',40],['double',30],['execute',40]],['maxhp',10],'moon',{b:'katana',L:3.6,metal:0xc8d8ff,edge:0xffffff,tsuba:0x6a4aa0,wrap:0x2a1a4a,rune:0xd8e0ff,flame:0xc0d0ff}],
 ['ronin_blade','Blade of the Wandering Ronin','weapon','katana',3,'Original (anime style)','A plain, chipped katana that has won a thousand duels.',[['crit',35]],null,'wind',{b:'katana',L:2.5,metal:0xb8c0c8,edge:0xe8eef0,tsuba:0x3a3a3a,wrap:0x5a1a1a,rune:0xffffff}],
 // pole
 ['spear_of_lugh','Spear of Lugh','weapon','pole',4,'Irish','So hungry for battle it had to be kept in a cauldron of water, or it would set the land alight.',[['burn',50],['pierce',0],['crit',25]],['selfburn',8],'fire',{b:'spear',head:'flame',L:4.4,metal:0xd04010,edge:0xffd080,accent:0xffcf4a,rune:0xff7a20,flame:0xff7a20}],
 ['tomoe_naginata','Naginata of Tomoe Gozen','weapon','pole',3,'Japanese','The legendary woman warrior’s glaive. It sweeps riders from their saddles.',[['execute',50],['double',15]],null,'wind',{b:'spear',head:'naginata',L:4.2,metal:0xe8eef6,edge:0xffffff,accent:0x8a1a1a,rune:0xffffff,wood:0x2a1a1a}],
 ['ruyi_staff','Ruyi Jingu Bang','weapon','pole',4,'Chinese','The Monkey King’s staff can shrink to a needle or grow to touch the sky.',[['quake',40],['double',30],['stun',20]],['slowskill',1],'sun',{b:'spear',head:'cap',L:4.6,metal:0xc02010,edge:0xffcf4a,accent:0xffcf4a,rune:0xffd040,wood:0xc02010}],
 ['trishula','Trishula of Shiva','weapon','pole',4,'Hindu','The trident that destroys the three worlds of illusion.',[['quake',35],['burn',35],['pierce',0]],['fragile',12],'fire',{b:'spear',head:'trishula',L:4.4,metal:0xd8dde3,edge:0xffffff,accent:0x2a6aa0,rune:0x80d0ff,flame:0x80d0ff}],
 ['athena_spear','Spear of Athena','weapon','pole',3,'Greek','Wisdom’s weapon: it strikes exactly where the enemy is weakest.',[['execute',55],['crit',15]],null,'holy',{b:'spear',head:'leaf',L:4.3,metal:0xe8d080,edge:0xffffff,accent:0x2a4a8a,rune:0xffe080}],
 ['wadjet_spear','Spear of Wadjet','weapon','pole',3,'Egyptian','Crowned with the cobra goddess. Its venom burns slowly.',[['burn',35],['pierce',0]],null,'underworld',{b:'spear',head:'cobra',L:4.2,metal:0xffcf4a,edge:0xfff0c0,accent:0x1a8a6a,rune:0x40ffa0}],
 // ranged
 ['neith_bow','Bow of Neith','weapon','ranged',3,'Egyptian','The huntress goddess crossed two arrows on her shield. Her bow never tires.',[['multishot',1],['crit',20]],null,'sun',{b:'bow',metal:0xffcf4a,edge:0xfff0c0,accent:0x1a6aa0,rune:0xffd040,deco:'sun'}],
 ['hachiman_yumi','Yumi of Hachiman','weapon','ranged',3,'Japanese','The war god’s tall bow. Its arrows sing as they fly.',[['crit',30],['pierce',0]],null,'wind',{b:'bow',metal:0x2a1a1a,edge:0xffffff,accent:0xc02020,rune:0xffffff,tall:1}],
 ['pinaka','Pinaka','weapon','ranged',4,'Hindu','Shiva’s great bow. One arrow from it burned three flying cities.',[['burn',45],['chain',40],['multishot',1]],['selfburn',8],'fire',{b:'bow',metal:0x2a4a8a,edge:0xffe080,accent:0xffcf4a,rune:0xff9020,deco:'sun'}],
 ['skadi_bow','Frostbow of Skaði','weapon','ranged',4,'Norse','The giantess of winter hunts on skis. Her arrows freeze where they land.',[['crit',40],['stun',25],['multishot',1]],['fragile',10],'rune',{b:'bow',metal:0xbfefff,edge:0xffffff,accent:0x6aa0d0,rune:0x9fe8ff,deco:'ice'}],
 // heavy
 ['perun_axe','Axe of Perun','weapon','heavy',3,'Slavic','The thunder god of the oak. Struck trees still smoke where his axe fell.',[['stun',25],['chain',25]],null,'thunder',{b:'axe',double:0,metal:0x8a96a8,edge:0xe8f6ff,accent:0x6a4422,rune:0x9fd8ff}],
 ['set_maul','Was-Maul of Set','weapon','heavy',4,'Egyptian','Set, lord of the red desert, ruled with this forked sceptre. Sandstorms rise where it lands.',[['quake',40],['burn',30],['stun',20]],['clumsy',6],'dragonfire',{b:'hammer',head:'was',metal:0xa02a10,edge:0xffcf4a,accent:0x1a1a1a,rune:0xff6a20}],
 ['oni_kanabo','Kanabō of the Oni','weapon','heavy',3,'Japanese','An iron club studded with spikes. “Like giving an oni a kanabō”: making the strong stronger.',[['stun',30],['double',10]],null,'blood',{b:'hammer',head:'kanabo',metal:0x2a2a30,edge:0xc0c0c8,accent:0xc02020,rune:0xff3030}],
 ['gogmagog_hammer','Hammer of Gogmagog','weapon','heavy',3,'British','The giant of Albion’s stone hammer. Hills are the dents it left.',[['quake',30],['stun',15]],null,'lion',{b:'hammer',head:'block',metal:0x8a8070,edge:0xd8d0c0,accent:0x5a7a3a,rune:0x9fe080}],
 ['sharur','Sharur, the Smasher of Thousands','weapon','heavy',4,'Mesopotamian','Ninurta’s talking mace. It flies ahead to scout, then returns to crush.',[['quake',35],['crit',30],['double',25]],['slowskill',1],'divine',{b:'hammer',head:'mace',metal:0x2a6aa0,edge:0xffcf4a,accent:0xffcf4a,rune:0x80d0ff}],
 ['surtr_sword','Sword of Surtr','weapon','heavy',4,'Norse','The fire giant’s blade, brighter than the sun. At Ragnarök it sets the world ablaze.',[['burn',60],['quake',30]],['selfburn',10],'dragonfire',{b:'sword',L:3.4,wd:0.55,guard:'cross',metal:0x3a1008,edge:0xff8a20,accent:0x1a0a04,rune:0xff6a10,flame:0xff6a10}],
 // scythe
 ['anubis_scythe','Crook-Scythe of Anubis','weapon','scythe',4,'Egyptian','The jackal god weighs every heart. Those found wanting are reaped.',[['lifesteal',30],['execute',60]],['maxhp',10],'underworld',{b:'scythe',metal:0x1a1a20,edge:0xffcf4a,accent:0xffcf4a,rune:0x40ffa0,flame:0x40ffa0,crook:1}],
 ['hel_scythe','Scythe of Hel','weapon','scythe',4,'Norse','Half her face is death. Half her blade is ice.',[['lifesteal',30],['stun',25],['chain',30]],['fragile',12],'soul',{b:'scythe',metal:0x3a4a5a,edge:0xbfefff,accent:0x1a1a20,rune:0x9fe8ff,flame:0xbfefff,skull:1}],
 ['shinigami_scythe','Shinigami’s Scythe','weapon','scythe',3,'Japanese','The death god’s harvest blade. Light as paper, sharp as a last breath.',[['lifesteal',20],['crit',20]],null,'soul',{b:'scythe',metal:0x101014,edge:0xd8e8ff,accent:0x6a1a8a,rune:0xc080ff}],
 ['morana_scythe','Sickle of Morana','weapon','scythe',3,'Slavic','The goddess of winter and death. Each spring her effigy is drowned; each winter she returns.',[['lifesteal',18],['stun',15]],null,'rune',{b:'scythe',metal:0xd8eef8,edge:0xffffff,accent:0x2a4a6a,rune:0x9fe8ff}],
 // staff (new archetype)
 ['crook_osiris','Crook of Osiris','weapon','staff',3,'Egyptian','The shepherd-king of the dead guides lost souls home.',[['lifesteal',15],['burn',20]],null,'underworld',{b:'staff',top:'crook',metal:0x1a6aa0,accent:0xffcf4a,rune:0x40ffa0}],
 ['ankh_isis','Ankh-Staff of Isis','weapon','staff',4,'Egyptian','The great mother’s key of life. She reassembled Osiris with it.',[['lifesteal',30],['chain',40],['burn',20]],['fragile',10],'holy',{b:'staff',top:'ankh',metal:0xffcf4a,accent:0x1a6aa0,rune:0xfff0a0,flame:0xfff0a0}],
 ['caduceus','Caduceus of Hermes','weapon','staff',3,'Greek','Two serpents and two wings. It sends enemies to sleep and souls to the underworld.',[['stun',25],['chain',20]],null,'wind',{b:'staff',top:'caduceus',metal:0xffcf4a,accent:0x2a8a5a,rune:0xffe080}],
 ['merlin_staff','Staff of Merlin','weapon','staff',3,'Arthurian','Gnarled oak capped with a star that remembers the future.',[['crit',25],['burn',20]],null,'holy',{b:'staff',top:'crystal',metal:0x5a3a20,accent:0x2a4a9a,rune:0x9fd8ff,wood:1}],
 ['gambanteinn','Gambanteinn','weapon','staff',4,'Norse','Odin’s wand of runes. Its curses are carved, not spoken.',[['chain',50],['crit',30]],['maxhp',10],'rune',{b:'staff',top:'rune',metal:0x3a3a48,accent:0x6fd0ff,rune:0x6fd0ff,flame:0x6fd0ff}],
 ['thyrsus','Thyrsus of Dionysus','weapon','staff',3,'Greek','A fennel staff tipped with a pine cone and wound with ivy. Madness follows it.',[['stun',20],['double',20]],null,'life',{b:'staff',top:'pine',metal:0x6a8a3a,accent:0x8a2a6a,rune:0x9fe080,wood:1}],
 ['asclepius_rod','Rod of Asclepius','weapon','staff',3,'Greek','The healer’s serpent staff. Every strike mends its bearer.',[['lifesteal',22]],null,'life',{b:'staff',top:'serpent',metal:0x7a5a30,accent:0x3a8a3a,rune:0x80ff90,wood:1}],
 ['ra_staff','Sun-Staff of Ra','weapon','staff',4,'Egyptian','The sun disk crowned with a cobra. It carries noon into the darkest tomb.',[['burn',55],['chain',30]],['selfburn',8],'sun',{b:'staff',top:'sun',metal:0xffcf4a,accent:0xc02010,rune:0xffd040,flame:0xffb020}],
 ['moon_princess_staff','Crystal Staff of the Moon Princess','weapon','staff',4,'Original (anime style)','A wand of crystal and starlight. When she calls, the moon itself answers.',[['crit',35],['chain',40],['stun',15]],['fragile',10],'moon',{b:'staff',top:'moon',metal:0xf0e8ff,accent:0xff9ad0,rune:0xffd0f0,flame:0xffd0f0}],
 // thrown (new archetype)
 ['sudarshana','Sudarshana Chakra','weapon','thrown',4,'Hindu','Vishnu’s spinning discus of a hundred blades. It returns after every kill.',[['chain',55],['crit',30],['multishot',1]],['fragile',10],'sun',{b:'chakram',kind:'star',metal:0xffcf4a,edge:0xfff0c0,rune:0xffb020,flame:0xffb020}],
 ['fujin_fan','War Fan of Fūjin','weapon','thrown',4,'Japanese','The wind god’s fan. One wave flattens a forest.',[['quake',35],['stun',25]],['clumsy',6],'wind',{b:'chakram',kind:'fan',metal:0x2a6a5a,edge:0xffffff,rune:0x9fffd8,flame:0xc0fff0}],
 ['apollo_discus','Discus of Apollo','weapon','thrown',3,'Greek','A bronze discus thrown by the sun god himself.',[['crit',25],['multishot',1]],null,'sun',{b:'chakram',kind:'disc',metal:0xcd8a3a,edge:0xffe0a0,rune:0xffd060}],
 ['night_shuriken','Shuriken of the Silent Night','weapon','thrown',3,'Original (anime style)','Four black blades, no sound. By the time you hear it, it has already returned.',[['double',25],['crit',20]],null,'raven',{b:'chakram',kind:'star4',metal:0x1a1a22,edge:0xc8d0e0,rune:0xc080ff}],
 ['tomoe_fan','Iron Fan of Tomoe','weapon','thrown',3,'Japanese','A samurai’s iron tessen: shield, signal flag and blade in one.',[['stun',20],['multishot',1]],null,'wind',{b:'chakram',kind:'fan',metal:0x3a3a40,edge:0xd8d8e0,rune:0xff4040}],
 ['khonsu_disc','Moon-Disc of Khonsu','weapon','thrown',3,'Egyptian','The moon god who travels the night sky. His crescent disc lights its own way back.',[['crit',25],['lifesteal',10]],null,'moon',{b:'chakram',kind:'ring',metal:0xe8eef6,edge:0xffffff,rune:0xd8e8ff}],
 ['durga_chakram','Chakram of Durga','weapon','thrown',3,'Hindu','One of the ten weapons the gods gave the warrior goddess to slay the buffalo demon.',[['chain',30],['double',15]],null,'divine',{b:'chakram',kind:'ring',metal:0xffcf4a,edge:0xfff0c0,rune:0xff6a20}],
 ['brisingamen_knuckles','Brísingamen Knuckles','weapon','fist',3,'Norse','Forged from Freyja’s fiery necklace of the dwarves. Beautiful and brutal.',[['burn',25],['double',20]],null,'fire',{b:'gaunt',metal:0xffcf4a,edge:0xffe0a0,accent:0xff6a20,rune:0xff9020}],
 ['murasame','Murasame','weapon','katana',3,'Original (anime style)','Dew forms on its blade when it is drawn, washing the blood away.',[['crit',25],['stun',15]],null,'wave',{b:'katana',L:2.6,metal:0xb8e0f0,edge:0xffffff,tsuba:0x2a6a8a,wrap:0x1a3a5a,rune:0x80e0ff}],
 // armour
 ['pharaoh_regalia','Regalia of the Pharaoh','armour','robe',3,'Egyptian','The double crown of Upper and Lower Egypt, and the gold collar of a god-king.',[['regen',4],['ward',8]],null,'sun',{c:0xf4f0e0,t:0xffcf4a,cape:0x1a6aa0,head:'nemes',collar:1,noCape:1}],
 ['anubis_mantle','Mantle of Anubis','armour','leather',4,'Egyptian','Wear the jackal’s face and the dead will make way.',[['evasion',20],['counter',30]],['fragile',8],'underworld',{c:0x14141a,t:0xffcf4a,cape:0x0a0a10,head:'jackal',collar:1}],
 ['horus_plate','Falcon Plate of Horus','armour','plate',3,'Egyptian','The sky god’s armour, with the Eye of Horus watching your back.',[['thorns',15],['ward',10]],null,'sun',{c:0x2a6aa0,t:0xffcf4a,cape:0x1a3a6a,head:'falcon',wingsBack:0x3a7ac0,collar:1}],
 ['ra_sunplate','Sunplate of Ra','armour','plate',4,'Egyptian','A golden shell crowned with the sun disk. It shines brighter the longer you stand.',[['ward',20],['thorns',25],['regen',2]],['clumsy',6],'sun',{c:0xffcf4a,t:0xff8a20,cape:0xc02010,head:'sundisk',collar:1}],
 ['mummy_wraps','Wrappings of the Undying','armour','leather',3,'Egyptian','Linen soaked in resin and spells. What it wraps does not die easily.',[['evasion',10],['regen',3]],null,'underworld',{c:0xd8ccb0,t:0x40ffa0,cape:0x8a7a60,head:'mummy',wraps:1,noCape:1}],
 ['scarab_shell','Shell of Khepri','armour','plate',3,'Egyptian','The scarab who rolls the sun across the sky. Its shell turns any blow.',[['ward',12],['thorns',12]],null,'sun',{c:0x1a5a4a,t:0x40ffd0,cape:0x0a2a2a,head:'scarab',shell:1,noCape:1}],
 ['isis_wings','Wings of Isis','armour','robe',4,'Egyptian','The mother goddess spreads her rainbow wings over the ones she protects.',[['regen',6],['phoenix',40]],['fragile',10],'holy',{c:0xf4f4ff,t:0x2a8aff,cape:0x1a4a9a,head:'vulture',wingsBack:0x5aa0ff,collar:1,noCape:1}],
 ['berserker_hide','Armour of the Berserker','armour','plate',4,'Norse','Berserkers wore the bear’s skin and fought without fear or pain. This black plate does the rest.',[['ward',15],['thorns',30],['regen',3]],['clumsy',10],'blood',{c:0x16161c,t:0xff2020,cape:0x3a2a1a,head:'berserker',bearskin:1,spikes:1,noCape:1,big:1}],
 ['valkyrie_plate','Plate of the Valkyries','armour','plate',3,'Norse','Chooser of the slain. White wings carry the worthy to Valhalla.',[['ward',12],['evasion',8]],null,'holy',{c:0xd8e0ea,t:0xffcf4a,cape:0x2a4a8a,head:'valkyrie',wingsBack:0xffffff}],
 ['fenrir_pelt','Pelt of Fenrir','armour','leather',4,'Norse','The wolf who will swallow the sun. Even his broken chain is part of the armour.',[['evasion',20],['counter',35]],['fragile',10],'raven',{c:0x3a3a44,t:0x9fe8ff,cape:0x2a2a30,head:'wolf',chainsX:1}],
 ['loki_guise','Guise of Loki','armour','leather',3,'Norse','The trickster’s green coat and twisted horns. Nothing about you is where it seems.',[['evasion',16],['counter',15]],null,'life',{c:0x1a4a2a,t:0xffcf4a,cape:0x0a2a14,head:'loki'}],
 ['jotunn_frost','Frost-Hide of the Jötnar','armour','plate',4,'Norse','Hewn from the glacier-skin of a frost giant. Cold enough to stop a heart.',[['ward',22],['thorns',20]],['clumsy',8],'rune',{c:0x9fc8e0,t:0xffffff,cape:0x4a7aa0,head:'jotunn',iceSpikes:1,big:1,noCape:1}],
 ['thor_mail','Mail of Thor','armour','plate',3,'Norse','Mail rings and a red cloak, with Megingjörð the belt of strength around the waist.',[['ward',10],['thorns',18]],null,'thunder',{c:0x8a96a8,t:0xffcf4a,cape:0xb02020,head:'thor',belt:1}],
 ['samurai_oyoroi','Ō-yoroi of the Shogun','armour','plate',3,'Japanese','Lacquered plates laced with silk, and a golden crescent on the helm.',[['ward',10],['thorns',15]],null,'wind',{c:0x8a1a1a,t:0xffcf4a,cape:0x1a1a1a,head:'kabuto',lamellar:1,noCape:1}],
 ['oni_lord','Armour of the Oni Lord','armour','plate',4,'Japanese','The mask of a demon king: horns, fangs and a temper like a volcano.',[['ward',18],['thorns',30]],['clumsy',6],'blood',{c:0x2a0a0a,t:0xff3020,cape:0x1a0505,head:'oni',lamellar:1,noCape:1}],
 ['kitsune_robe','Robe of the Nine-Tailed Fox','armour','robe',4,'Japanese','A thousand-year-old fox spirit. Each tail is a life.',[['regen',5],['evasion',15],['phoenix',30]],['fragile',8],'moon',{c:0xf4f0f8,t:0xff6a3a,cape:0xc02040,head:'kitsune',tails9:1,noCape:1}],
 ['raijin_ring','Drum-Ring of Raijin','armour','robe',3,'Japanese','A ring of drums floats behind the thunder god. Each beat is a lightning strike.',[['regen',4],['counter',15]],null,'thunder',{c:0x2a3a8a,t:0xfff080,cape:0x1a1a4a,head:'oni',drums:1,noCape:1}],
 ['ronin_haori','Haori of the Wandering Ronin','armour','leather',3,'Original (anime style)','A straw hat, a patched coat and a calm that frightens armies.',[['evasion',14],['counter',15]],null,'wind',{c:0x3a3a5a,t:0xe8e0c0,cape:0x2a2a40,head:'strawhat',haori:1,noCape:1}],
 ['wukong_regalia','Regalia of the Monkey King','armour','leather',4,'Chinese','The Great Sage Equal to Heaven: golden circlet, phoenix plumes and cloud-walking boots.',[['evasion',20],['counter',30]],['fragile',10],'sun',{c:0xffcf4a,t:0xc02010,cape:0xc02010,head:'circlet'}],
 ['jade_emperor','Robe of the Jade Emperor','armour','robe',4,'Chinese','The ruler of heaven’s dragon robe and jade crown.',[['regen',6],['ward',12]],['clumsy',6],'life',{c:0xffcf4a,t:0x3ac080,cape:0x2a8a5a,head:'jadecrown',dragonRobe:1,noCape:1}],
 ['guan_plate','Green Dragon General’s Plate','armour','plate',3,'Chinese','The armour of a general so loyal he became a god.',[['ward',12],['thorns',12]],null,'life',{c:0x2a6a3a,t:0xffcf4a,cape:0xb02020,head:'general'}],
 ['cuchulainn_gear','War-Gear of Cú Chulainn','armour','leather',3,'Irish','The Hound of Ulster’s battle gear. In his rage the hero light shone from his head.',[['evasion',12],['counter',20]],null,'fire',{c:0x2a5a3a,t:0xffcf4a,cape:0x8a2a20,head:'celtic'}],
 ['morrigan_feathers','Feather-Cloak of the Morrígan','armour','robe',3,'Irish','The phantom queen’s cloak of raven feathers. Battles turn where she lands.',[['regen',4],['evasion',10]],null,'raven',{c:0x14141c,t:0xc02040,cape:0x0a0a10,head:'ravenhood',featherCloak:1,noCape:1}],
 ['karna_kavacha','Kavacha of Karna','armour','plate',4,'Hindu','Golden armour Karna was born wearing, a gift of the sun god. It could not be pierced.',[['ward',25],['regen',3]],['clumsy',8],'sun',{c:0xffcf4a,t:0xff8a20,cape:0xc06010,head:'sunhelm',sunRing:1}],
 ['mecha_frame','Starfall Mecha Frame','armour','plate',4,'Original (anime style)','A pilot’s battle frame. Thrusters, a glowing reactor core and a visor that never sleeps.',[['ward',20],['counter',25]],['clumsy',8],'divine',{c:0xe8eef6,t:0x40c0ff,cape:0x2a4a8a,head:'mecha',core:1,thrusters:1,noCape:1,big:1}],
 ['moon_hunter_coat','Moonlit Hunter’s Coat','armour','leather',3,'Original (anime style)','A long coat, a tricorn and a silver blade’s worth of nightmares behind you.',[['evasion',14],['counter',18]],null,'moon',{c:0x1a1a24,t:0xd8e0ff,cape:0x14141c,head:'tricorn',longcoat:1,noCape:1}],
 ['shinobi_garb','Spirit Shinobi Garb','armour','leather',3,'Original (anime style)','Masked, silent and gone. Only the long scarf is ever seen.',[['evasion',18]],null,'raven',{c:0x1a1a2a,t:0xff3040,cape:0xc02030,head:'shinobi',scarf:1,noCape:1}],
 ['starforged_paladin','Starforged Paladin Plate','armour','plate',3,'Original (anime style)','White and gold plate with a halo of floating swords.',[['ward',12],['thorns',15]],null,'holy',{c:0xf4f4ff,t:0xffcf4a,cape:0x2a4aa0,head:'paladin',swordHalo:1}]];

LEGENDS.push(...LEGENDS2);
const SPECIAL = {
  atomic:{kind:'weapon', name:'Slime Sword: “I Am Atomic”', arch:'blade', type:'Slime Sword', abil:[['quake',70],['crit',35]], down:['maxhp',12], text:'A homage to a certain shadow-garden master. Every hit sends a shockwave through all enemies.'},
  shadow:{kind:'armour', name:'Bodysuit of the Shadow Garden', role:'leather', abil:[['evasion',18],['counter',40]], down:['fragile',8], text:'Black slime woven into a bodysuit. Strike from the shadows.'}};
return {MYTHT1, SIGX, ARCHMOVES, BASICMOVE, STATUS_TEXT, SIGS, GOD_TEXT, LEGENDS, SPECIAL, BOONS, EVENTS, SHOP, RAR, SKILLS, WORLDS, LEG, MYTH, MYTH_DOWN, ARM_ROLE, LEG_ARM, MYTH_ARM, TRINKETS, TRINKET_TEXT, CONSUMABLES, ABIL_TEXT, ENEMIES, TRAITS, LTQ};
})();
