/* ===== Essay Quest v8 data (B): the armour catalogue =====
   70 designs:  15 base designs, each worn at Common, Uncommon and Rare (iron → steel → runed) ·
                15 Epic designs · 13 Legendary + 12 Mythical designs from the myths of each land · 15 Outerversal designs.
   `look` is read by GEAR3D.armourModel (12b): every part is optional.
     h helm · hc helm colour · eye visor/eye glow · horn [type, colour] · plume colour · sh shoulders · ch chest · em emblem
     sk skirt · ar arms · lg legs · cape [type, colour, colour2] · fx extras · pal [metal, trim, cloth, accent] · glow emissive lines
   Lands: 0 Greenlands · 1 Storm Coast · 2 Hollow Wastes · 3 Icelands · 4 Japan (Yamato) · 5 Greece (Hellas) */
(() => {
const D = DATA;
const A = (key, name, role, tier, lands, look, o) => Object.assign({key, name, role, tier, lands, look}, o || {});
// ---------- 15 base designs (Common / Uncommon / Rare) ----------
const BASE = [
  A('footman', 'Footman’s Plate', 'plate', 'base', [0, 3], {h:'kettle', sh:'round', ch:'plate', sk:'tassets', ar:'gauntlet', lg:'greaves', cape:['none']}),
  A('knight', 'Knight’s Harness', 'plate', 'base', [0, 1], {h:'barbute', plume:0xc03030, sh:'layer', ch:'plate', em:'cross', sk:'tabard', ar:'gauntlet', lg:'plate', cape:['short']}),
  A('hoplite', 'Hoplite Bronze', 'plate', 'base', [5], {h:'corinthian', plume:0xc02020, sh:'round', ch:'muscle', sk:'pteruges', ar:'bracer', lg:'greaves', cape:['short'], metal:'bronze'}),
  A('ashigaru', 'Ashigaru Dō', 'plate', 'base', [4], {h:'jingasa', sh:'sode', ch:'lamellar', em:'mon', sk:'kusazuri', ar:'bracer', lg:'greaves', cape:['none'], metal:'lacquer'}),
  A('sentinel', 'Sentinel Mail', 'plate', 'base', [1, 2, 3], {h:'greathelm', sh:'round', ch:'chain', sk:'tabard', em:'star', ar:'gauntlet', lg:'boots', cape:['long']}),
  A('ranger', 'Ranger Leathers', 'leather', 'base', [0, 3], {h:'hood', sh:'none', ch:'leather', sk:'coat', ar:'bracer', lg:'boots', cape:['short']}),
  A('scout', 'Scout Jerkin', 'leather', 'base', [1, 5], {h:'cap', sh:'round', ch:'leather', sk:'none', ar:'bracer', lg:'boots', cape:['scarf']}),
  A('wraps', 'Desert Wraps', 'leather', 'base', [2], {h:'wrap', sh:'none', ch:'leather', sk:'robe', ar:'cloth', lg:'boots', cape:['scarf']}),
  A('furs', 'Hunter’s Furs', 'leather', 'base', [3, 4], {h:'wolfhood', sh:'fur', ch:'leather', sk:'fur', ar:'bracer', lg:'boots', cape:['fur']}),
  A('corsair', 'Corsair Coat', 'leather', 'base', [1], {h:'tricorn', sh:'none', ch:'leather', sk:'coat', ar:'cloth', lg:'boots', cape:['none']}),
  A('acolyte', 'Acolyte Robe', 'robe', 'base', [0, 5], {h:'hood', sh:'none', ch:'robe', sk:'robe', ar:'cloth', lg:'cloth', cape:['none'], em:'sun'}),
  A('scholar', 'Scholar’s Vestments', 'robe', 'base', [2, 5], {h:'circlet', sh:'none', ch:'robe', sk:'robe', ar:'cloth', lg:'cloth', cape:['long'], fx:['books']}),
  A('shrine', 'Shrine Robes', 'robe', 'base', [4], {h:'eboshi', sh:'none', ch:'gi', sk:'hakama', ar:'cloth', lg:'cloth', cape:['none'], fx:['shimenawa']}),
  A('mystic', 'Mystic Wraps', 'robe', 'base', [1, 2], {h:'veil', sh:'none', ch:'robe', sk:'robe', ar:'cloth', lg:'cloth', cape:['scarf']}),
  A('warden', 'Warden Cloak', 'robe', 'base', [3, 4], {h:'cowl', sh:'fur', ch:'robe', sk:'robe', ar:'bracer', lg:'boots', cape:['long']})];
// three tiers of the same design: iron/leather → steel with green → blued steel with gold and runes
D.BASE_TIER = [
  {pre:['Worn', 'Patched', 'Plain'], metal:0x8a8f96, trim:0x6a5038, cloth:0x7a6a55, accent:0x9a8a70, glow:0},
  {pre:['Fine', 'Sturdy', 'Woven'], metal:0xb8c0c8, trim:0x3f8a4a, cloth:0x3f6a48, accent:0x7fd08a, glow:0},
  {pre:['Runed', 'Masterwork', 'Enchanted'], metal:0x9fb4d8, trim:0xd8b048, cloth:0x2a4a8a, accent:0x6fb8ff, glow:0x6fb8ff}];
D.BASE_METAL = {bronze:[0xa86a2a, 0xc88a3a, 0xe0a850], lacquer:[0x3a2a26, 0x5a2020, 0x1a1a2a]};

// ---------- 15 Epic designs ----------
const EPIC = [
  A('dreadhorn', 'Dreadhorn Plate', 'plate', 'epic', [0, 3], {h:'greathelm', horn:['long', 0x2a2a30], eye:0xff3030, sh:'spike', ch:'ribs', sk:'tassets', ar:'claw', lg:'plate', cape:['tattered', 0x1a1a20], pal:[0x55575e, 0x2a2b30, 0x1e1e24, 0x8a8d96], glow:0}),
  A('sunforged', 'Sunforged Aegis', 'plate', 'epic', [2, 5], {h:'visor', horn:['crescent', 0xd8b048], eye:0xfff080, sh:'blade', ch:'core', em:'sun', sk:'tassets', ar:'gauntlet', lg:'plate', cape:['none'], pal:[0x1a1a1e, 0xd8b048, 0x101014, 0xfff080], glow:0xffe060}),
  A('obsidian', 'Obsidian Juggernaut', 'plate', 'epic', [2, 4], {h:'greathelm', eye:0xff6020, sh:'layer', ch:'plate', sk:'tassets', ar:'gauntlet', lg:'plate', cape:['none'], fx:['cracks', 'spikes'], pal:[0x1c1820, 0x3a3038, 0x14101a, 0xff6020], glow:0xff5010}),
  A('stormcaller', 'Stormcaller Plate', 'plate', 'epic', [1, 5], {h:'winged', eye:0x9fe8ff, sh:'wing', ch:'plate', em:'bolt', sk:'tassets', ar:'gauntlet', lg:'greaves', cape:['long', 0x2a4a8a, 0x9fe8ff], fx:['sparks'], pal:[0x5a6a88, 0xe8f0ff, 0x2a3a6a, 0x9fe8ff], glow:0x9fe8ff}),
  A('bloodmoon', 'Bloodmoon Warplate', 'plate', 'epic', [0, 4], {h:'kabuto', horn:['oni', 0x8a1010], eye:0xff2040, sh:'sode', ch:'lamellar', em:'moon', sk:'kusazuri', ar:'gauntlet', lg:'greaves', cape:['none'], pal:[0x3a0e14, 0x8a1010, 0x1a0a0e, 0xff3050], glow:0xff2040}),
  A('nightstalker', 'Nightstalker Garb', 'leather', 'epic', [0, 2], {h:'mask', eye:0xb06cff, sh:'none', ch:'leather', sk:'coat', ar:'claw', lg:'boots', cape:['tattered', 0x14101c], fx:['smoke'], pal:[0x1c1a24, 0x3a3048, 0x121018, 0xb06cff], glow:0xb06cff}),
  A('venomfang', 'Venomfang Leathers', 'leather', 'epic', [1, 2], {h:'hood', eye:0x7fff60, sh:'spike', ch:'scale', sk:'coat', ar:'claw', lg:'boots', cape:['short', 0x1a3a1a], fx:['drip'], pal:[0x2a4a2a, 0x8ac030, 0x1a2a1a, 0x7fff60], glow:0x7fff60}),
  A('frostfang', 'Frostfang Pelt', 'leather', 'epic', [3], {h:'wolfhood', eye:0x9fe8ff, sh:'fur', ch:'leather', sk:'fur', ar:'claw', lg:'boots', cape:['fur', 0xe8f4ff], fx:['icicles'], pal:[0x8aa8c0, 0xe8f4ff, 0x4a6a80, 0x9fe8ff], glow:0x9fe8ff}),
  A('windrunner', 'Windrunner Coat', 'leather', 'epic', [4, 5], {h:'band', sh:'none', ch:'leather', sk:'coat', ar:'bracer', lg:'boots', cape:['scarf', 0x30c0a0, 0x9fffe8], fx:['wind'], pal:[0x3a6a5a, 0xe8f0e0, 0x2a4a40, 0x9fffe8], glow:0x9fffe8}),
  A('crimsoncorsair', 'Crimson Corsair', 'leather', 'epic', [1, 3], {h:'tricorn', plume:0xff3040, sh:'round', ch:'leather', sk:'coat', ar:'bracer', lg:'boots', cape:['long', 0x8a1020, 0xd8b048], pal:[0x5a1018, 0xd8b048, 0x2a0a10, 0xff4050], glow:0}),
  A('arcanist', 'Arcanist Regalia', 'robe', 'epic', [0, 5], {h:'circlet', eye:0xc08aff, sh:'orb', ch:'robe', em:'eye', sk:'robe', ar:'cloth', lg:'cloth', cape:['long', 0x3a1a6a, 0xc08aff], fx:['runes'], pal:[0x4a2a8a, 0xd8b048, 0x2a1a4a, 0xc08aff], glow:0xc08aff}),
  A('embersage', 'Ember Sage Robe', 'robe', 'epic', [2, 4], {h:'hood', eye:0xff8a3c, sh:'none', ch:'robe', em:'sun', sk:'robe', ar:'cloth', lg:'cloth', cape:['long', 0x6a1a0a, 0xff8a3c], fx:['embers'], pal:[0x8a2a10, 0xffb040, 0x3a0e08, 0xff8a3c], glow:0xff8a3c}),
  A('tidecaller', 'Tidecaller Vestments', 'robe', 'epic', [1], {h:'crown', eye:0x6fd8ff, sh:'shell', ch:'robe', em:'trident', sk:'robe', ar:'cloth', lg:'cloth', cape:['long', 0x1a4a7a, 0x6fd8ff], fx:['bubbles'], pal:[0x2a6a8a, 0xe8d8a0, 0x14304a, 0x6fd8ff], glow:0x6fd8ff}),
  A('voidweave', 'Voidweave Shroud', 'robe', 'epic', [3, 4], {h:'cowl', eye:0x8a6ae0, sh:'none', ch:'robe', sk:'robe', ar:'cloth', lg:'cloth', cape:['tattered', 0x0e0a18, 0x8a6ae0], fx:['orbs'], pal:[0x1a1428, 0x8a6ae0, 0x0e0a18, 0xb09aff], glow:0x8a6ae0}),
  A('starlit', 'Starlit Oracle', 'robe', 'epic', [3, 5], {h:'halo', eye:0xfff4c0, sh:'none', ch:'robe', em:'star', sk:'robe', ar:'cloth', lg:'cloth', cape:['long', 0x101838, 0xfff4c0], fx:['stars'], pal:[0xe8e8f4, 0xd8b048, 0x1a2450, 0xfff4c0], glow:0xfff4c0})];

// ---------- 13 Legendary + 12 Mythical: the myths of each land ----------
const L = 'legend', M = 'myth';
const MYTHS = [
  // Greenlands: Arthurian and Irish legend
  A('pendragon', 'Pendragon Plate', 'plate', L, [0], {h:'crown', eye:0xfff0a0, sh:'dragon', ch:'plate', em:'dragon', sk:'tabard', ar:'gauntlet', lg:'plate', cape:['long', 0xa01818, 0xffd040], pal:[0xd8dde4, 0xffcf4a, 0xa01818, 0xfff0a0], glow:0xfff0a0}, {origin:'Arthurian', lore:'Forged for the once and future king. The red dragon on the breast wakes when Britain is in need.', abil:[['bulwark', 10], ['ward', 10]]}),
  A('greenknight', 'Green Knight’s Mantle', 'leather', L, [0], {h:'holly', eye:0x7fff60, sh:'leaf', ch:'leather', sk:'coat', ar:'bracer', lg:'boots', cape:['long', 0x1a5a1a, 0x7fd04a], fx:['vines', 'leaves'], pal:[0x2a6a2a, 0xc8a040, 0x1a3a1a, 0x7fff60], glow:0x7fff60}, {origin:'Arthurian', lore:'He picked up his own head and rode away laughing. His mantle mends any wound by the next new year.', abil:[['evasion', 10], ['regen', 3]]}),
  A('morrigan', 'Morrígan’s Raven Shroud', 'robe', M, [0], {h:'ravenhelm', eye:0xff3040, sh:'feather', ch:'robe', sk:'robe', ar:'claw', lg:'cloth', cape:['wings', 0x0e0e14, 0x3a1a4a], fx:['ravens', 'smoke'], pal:[0x16141c, 0x6a1a2a, 0x0e0e14, 0xff3040], glow:0xff3040}, {origin:'Irish', lore:'The phantom queen of battle washes the armour of those about to die. Wear it, and choose who that is.', abil:[['regen', 4], ['expose', 25], ['counter', 25]], down:['fragile', 8]}),
  A('riastrad', 'Cú Chulainn’s Riastrad', 'plate', M, [0], {h:'barbute', horn:['spire', 0xc02020], eye:0xff2020, sh:'spike', ch:'ribs', sk:'tassets', ar:'claw', lg:'plate', cape:['tattered', 0x6a0a0a], fx:['spikes', 'blood'], pal:[0x5a5a64, 0xc02020, 0x2a0a0a, 0xff4040], glow:0xff2020}, {origin:'Irish', lore:'The warp-spasm: Ulster’s hound twists into a monster of spikes and fury that no army can stand before.', abil:[['thorns', 30], ['vengeance', 6], ['ward', 10]], down:['bleed', 2]}),
  // Storm Coast: the drowned kingdoms of the sea
  A('atlantean', 'Atlantean Tideplate', 'plate', L, [1], {h:'crest', plume:0x30c0d0, eye:0x6fd8ff, sh:'shell', ch:'scale', em:'trident', sk:'tassets', ar:'gauntlet', lg:'greaves', cape:['long', 0x0e4a6a, 0x6fd8ff], fx:['bubbles'], pal:[0x2a8a9a, 0xe8d090, 0x0e3a5a, 0x6fd8ff], glow:0x6fd8ff}, {origin:'Atlantean', lore:'Orichalcum scales from the city beneath the waves. The tide itself will not drown its wearer.', abil:[['ward', 12], ['regen', 2]]}),
  A('selkie', 'Selkie Sealskin', 'leather', L, [1], {h:'sealhood', eye:0x9fe8ff, sh:'fur', ch:'leather', sk:'coat', ar:'bracer', lg:'boots', cape:['fur', 0x4a5a6a], fx:['bubbles'], pal:[0x5a6a7a, 0xd8e0e8, 0x3a4a5a, 0x9fe8ff], glow:0x9fe8ff}, {origin:'Celtic sea-lore', lore:'Steal a selkie’s skin and she must stay ashore. Wear it, and you slip between blows like a seal through surf.', abil:[['evasion', 12], ['counter', 15]]}),
  A('leviathan', 'Leviathan Abyssplate', 'plate', M, [1], {h:'maw', eye:0x30ffd0, sh:'fin', ch:'scale', sk:'tassets', ar:'claw', lg:'plate', cape:['tattered', 0x0a2a3a, 0x30ffd0], fx:['tentacles', 'bubbles'], pal:[0x0e3a4a, 0x30a090, 0x06141c, 0x30ffd0], glow:0x30ffd0}, {origin:'Biblical sea-lore', lore:'Scales of the beast no hook can draw out. Its jaws close over the wearer’s face like a helmet.', abil:[['ward', 18], ['thorns', 25], ['regen', 2]], down:['clumsy', 6]}),
  A('sirenqueen', 'Siren Queen’s Pearl Robes', 'robe', M, [1], {h:'crown', eye:0xff9ae8, sh:'shell', ch:'robe', em:'pearl', sk:'robe', ar:'cloth', lg:'cloth', cape:['long', 0x2a8a8a, 0xff9ae8], fx:['pearls', 'bubbles'], pal:[0xe8f4f0, 0xff9ae8, 0x1a6a6a, 0xffd0f0], glow:0xff9ae8}, {origin:'Greek sea-lore', lore:'The song that wrecked a thousand ships. Foes who hear it forget why they came.', abil:[['regen', 4], ['weaken', 25], ['mend', 2]], down:['fragile', 6]}),
  // Hollow Wastes: Egypt
  A('anubis', 'Jackal Plate of Anubis', 'plate', L, [2], {h:'jackal', eye:0xffcf4a, sh:'blade', ch:'plate', em:'ankh', sk:'pteruges', ar:'gauntlet', lg:'greaves', cape:['none'], pal:[0x16141a, 0xffcf4a, 0x1a6aa0, 0xffe080], glow:0xffcf4a}, {origin:'Egyptian', lore:'The weigher of hearts guards the dead. Its wearer’s heart weighs no more than a feather.', abil:[['lastStand', 1], ['ward', 10]]}),
  A('pharaoh', 'Sun Robes of the Pharaoh', 'robe', L, [2], {h:'nemes', eye:0xffe060, sh:'collar', ch:'robe', em:'sun', sk:'robe', ar:'cloth', lg:'sandal', cape:['none'], fx:['embers'], pal:[0xf0e8d0, 0xffcf4a, 0x1a6aa0, 0xffe060], glow:0xffe060}, {origin:'Egyptian', lore:'Linen of the god-kings, woven with gold thread spun from noon.', abil:[['regen', 3], ['mend', 2]]}),
  A('ra', 'Solar Disc of Ra', 'plate', M, [2], {h:'falcon', eye:0xffa020, sh:'wing', ch:'core', em:'sun', sk:'pteruges', ar:'gauntlet', lg:'greaves', cape:['wings', 0xffcf4a, 0xff8020], fx:['sundisc', 'embers'], pal:[0xffcf4a, 0x1a6aa0, 0xa0400a, 0xfff0a0], glow:0xffa020}, {origin:'Egyptian', lore:'The sun boat sails the sky by day and the underworld by night. Its disc burns over your head.', abil:[['thorns', 25], ['regen', 3], ['ward', 12]], down:['tired', 5]}),
  A('apophis', 'Coil of Apophis', 'leather', M, [2], {h:'cobra', eye:0x9a30ff, sh:'scale', ch:'scale', sk:'coat', ar:'claw', lg:'boots', cape:['tattered', 0x1a0a2a, 0x9a30ff], fx:['coils', 'smoke'], pal:[0x2a1440, 0x6a3a9a, 0x0e0818, 0x9a30ff], glow:0x9a30ff}, {origin:'Egyptian', lore:'The serpent of chaos swallows the sun each night. Its scales drink light and strike from the dark.', abil:[['evasion', 15], ['counter', 30], ['poison', 25]], down:['bleed', 2]}),
  // Icelands: Norse
  A('einherjar', 'Einherjar Wolfplate', 'plate', L, [3], {h:'wolfhelm', eye:0x9fe8ff, sh:'fur', ch:'chain', em:'wolf', sk:'fur', ar:'gauntlet', lg:'greaves', cape:['fur', 0x8a8a90], fx:['runes'], pal:[0x8a96a8, 0xd8c890, 0x4a3a2a, 0x9fe8ff], glow:0x9fe8ff}, {origin:'Norse', lore:'The chosen dead of Valhalla fight every day and are whole again by night.', abil:[['regen', 3], ['thorns', 15]]}),
  A('valkyrie', 'Valkyrie Wingmail', 'leather', L, [3], {h:'winged', eye:0xfff4c0, sh:'wing', ch:'chain', sk:'tassets', ar:'bracer', lg:'boots', cape:['long', 0xe8e8f0, 0xd8b048], fx:['feathers'], pal:[0xdfe6ee, 0xd8b048, 0x6a7a9a, 0xfff4c0], glow:0xfff4c0}, {origin:'Norse', lore:'The choosers of the slain ride over every battlefield. No blow lands on one who chooses.', abil:[['evasion', 12], ['warcry', 8]]}),
  A('allfather', 'Allfather’s Wanderer Cloak', 'robe', M, [3], {h:'widehat', eye:0x9fe8ff, sh:'fur', ch:'robe', sk:'robe', ar:'cloth', lg:'boots', cape:['cloak', 0x2a3a5a, 0x9fe8ff], fx:['ravens', 'runes'], pal:[0x3a4a6a, 0xd8c890, 0x1a2234, 0x9fe8ff], glow:0x9fe8ff, oneEye:1}, {origin:'Norse', lore:'He gave an eye for wisdom and hung nine nights on the world tree. Huginn and Muninn bring him every secret.', abil:[['regen', 4], ['mend', 3], ['energize', 8]], down:['maxhp', 8]}),
  A('fenrir', 'Fenrir-Bound Hide', 'leather', M, [3], {h:'wolfmaw', eye:0xffcf4a, sh:'fur', ch:'leather', sk:'fur', ar:'claw', lg:'boots', cape:['fur', 0x2a2a30], fx:['chains', 'smoke'], pal:[0x2a2a30, 0x8a8a90, 0x16161a, 0xffcf4a], glow:0xffcf4a}, {origin:'Norse', lore:'The wolf who will swallow the sun, still wearing the ribbon that binds him. It holds… for now.', abil:[['evasion', 14], ['vengeance', 6], ['counter', 30]], down:['bleed', 2]}),
  // Japan: Shintō and the samurai
  A('onikabuto', 'Oni-Kabuto Ō-yoroi', 'plate', L, [4], {h:'kabuto', horn:['oni', 0xd8b048], eye:0xff3030, sh:'sode', ch:'lamellar', em:'mon', sk:'kusazuri', ar:'gauntlet', lg:'greaves', cape:['none'], fx:['menpo'], pal:[0x2a1a1a, 0xd8b048, 0x8a1010, 0xff3030], glow:0xff3030}, {origin:'Japanese', lore:'A daimyō’s great armour, its mask carved as a grinning oni so his enemies saw a demon coming.', abil:[['ward', 10], ['thorns', 20]]}),
  A('kitsune', 'Kitsune Shrine Robes', 'robe', L, [4], {h:'foxmask', eye:0xffa040, sh:'none', ch:'gi', sk:'hakama', ar:'cloth', lg:'cloth', cape:['none'], fx:['tails9', 'foxfire'], pal:[0xf4f0e8, 0xc02020, 0xc02020, 0xffa040], glow:0xffa040}, {origin:'Japanese', lore:'Inari’s messengers grow a tail for every hundred years. Nine tails, and they hear the whole world.', abil:[['regen', 3], ['evasion', 6]]}),
  A('susanoo', 'Susanoo Storm-God Armour', 'plate', M, [4], {h:'kabuto', horn:['spire', 0x9fe8ff], eye:0x9fe8ff, sh:'sode', ch:'lamellar', em:'bolt', sk:'kusazuri', ar:'gauntlet', lg:'greaves', cape:['energy', 0x6a8aff, 0x9fe8ff], fx:['spirit', 'sparks'], pal:[0x1a2a5a, 0x9fe8ff, 0x0e1430, 0xe8f4ff], glow:0x9fe8ff}, {origin:'Japanese', lore:'The storm god who slew the eight-headed Orochi. His spirit stands behind you as a giant of lightning.', abil:[['ward', 16], ['thorns', 25], ['amp', 8]], down:['tired', 5]}),
  A('raijin', 'Raijin Thunder-Drum Harness', 'leather', M, [4], {h:'oni', horn:['oni', 0xfff080], eye:0xfff080, sh:'none', ch:'gi', sk:'tiger', ar:'bracer', lg:'cloth', cape:['none'], fx:['drums', 'sparks'], pal:[0x2a4a8a, 0xfff080, 0xd88a20, 0xfff8c0], glow:0xfff080}, {origin:'Japanese', lore:'The thunder god beats a ring of drums in the clouds. Each beat is a lightning strike.', abil:[['evasion', 14], ['counter', 30], ['chain', 30]], down:['fragile', 8]}),
  // Greece: the heroes and gods of Olympus
  A('achilles', 'Aegis of Achilles', 'plate', L, [5], {h:'corinthian', plume:0xd02020, eye:0xffe080, sh:'round', ch:'muscle', em:'lion', sk:'pteruges', ar:'bracer', lg:'greaves', cape:['long', 0xa01818], pal:[0xd8a040, 0xfff0c0, 0xa01818, 0xffe080], glow:0xffe080, metal:'gold'}, {origin:'Greek', lore:'Hephaestus forged it in a single night. Only the heel was left bare.', abil:[['ward', 12], ['thorns', 15]]}),
  A('nemean', 'Nemean Lionhide', 'leather', L, [5], {h:'lionhead', eye:0xffcf4a, sh:'fur', ch:'muscle', sk:'fur', ar:'bracer', lg:'sandal', cape:['fur', 0xc89040], pal:[0xc89040, 0xffe8a0, 0x8a5a20, 0xffcf4a], glow:0}, {origin:'Greek', lore:'Heracles strangled the lion whose hide no blade could cut, then wore it with its jaws as a helm.', abil:[['evasion', 10], ['ward', 10]]}),
  A('hades', 'Helm of Hades', 'plate', M, [5], {h:'hadeshelm', eye:0x40ffb0, sh:'skull', ch:'ribs', sk:'tassets', ar:'claw', lg:'plate', cape:['tattered', 0x0a0a10, 0x40ffb0], fx:['soulfire', 'smoke'], pal:[0x1a1a22, 0x40ffb0, 0x0a0a10, 0x9affd8], glow:0x40ffb0}, {origin:'Greek', lore:'The Cyclopes forged the helm of darkness. Who wears it walks unseen, and the dead kneel.', abil:[['evasion', 10], ['ward', 14], ['lastStand', 1]], down:['bleed', 2]}),
  A('zeus', 'Regalia of Zeus', 'robe', M, [5], {h:'laurel', eye:0xfff080, sh:'cloud', ch:'robe', em:'bolt', sk:'robe', ar:'bracer', lg:'sandal', cape:['long', 0xe8f0ff, 0x9fe8ff], fx:['sparks', 'clouds'], pal:[0xf4f4f0, 0xffcf4a, 0x4a6aa0, 0xfff080], glow:0xfff080}, {origin:'Greek', lore:'The robes of the king of Olympus crackle with the bolts the Cyclopes made him.', abil:[['regen', 4], ['chain', 35], ['amp', 8]], down:['fragile', 8]}),
  // anywhere: the black swordsman's armour
  A('dragonslayer', 'Armour of the Black Swordsman', 'plate', L, [0, 1, 2, 3, 4, 5], {h:'beast', eye:0xff2020, sh:'layer', ch:'plate', sk:'tassets', ar:'gauntlet', lg:'plate', cape:['tattered', 0x0e0e12], fx:['hair', 'scratches'], pal:[0x3a3a40, 0x8a8a90, 0x16161a, 0xff2020], glow:0xff2020}, {origin:'Dragon slayer', lore:'Forged for the one who slays dragons and the demons behind them. It bites back at the wearer’s mind.', abil:[['vengeance', 5], ['lastStand', 1]], bs:{hp:320, def:90, spd:70, spe:30}})];

// ---------- 15 Outerversal designs (homages; nothing here is an official design) ----------
const O = 'outer';
const OUTER = [
  A('primal_steel_armour', 'Warplate of the Prime Sun-Lord', 'plate', O, [], {h:'none', hair:0x101018, eye:0xff2020, sh:'round', ch:'muscle', em:'hope', sk:'none', ar:'gauntlet', lg:'boots', cape:['long', 0xc01818, 0xffcf4a], fx:['aura'], pal:[0x1a3a9a, 0xffcf4a, 0xc01818, 0xff4040], glow:0xff4040}, {origin:'Last Sun (homage)', lore:'Armour for a god who chose to be a farmer’s son. Under a red sun it hums; under a yellow one it sings.', abil:[['ward', 22], ['regen', 4], ['bulwark', 10]], down:['tired', 5]}),
  A('cowl_grinning_bat', 'Cowl of the Grinning Bat-King', 'leather', O, [], {h:'batcrown', eye:0xff3030, sh:'spike', ch:'leather', em:'bat', sk:'coat', ar:'claw', lg:'boots', cape:['tattered', 0x0a0a0e, 0x2a2a30], fx:['grin', 'chains'], pal:[0x16161a, 0x5a5a64, 0x0a0a0e, 0xff3030], glow:0xff3030}, {origin:'Dark Multiverse (homage)', lore:'What happens when the world’s greatest detective stops fighting the joke and becomes it.', abil:[['evasion', 18], ['counter', 40], ['expose', 30]], down:['bleed', 2]}),
  A('crescent_crusader_mantle', 'Mantle of the Crescent Crusader', 'robe', O, [], {h:'mummyhood', eye:0xe8f0ff, sh:'none', ch:'robe', em:'moon', sk:'robe', ar:'bracer', lg:'boots', cape:['cloak', 0xf4f4f8, 0xcdd8ff], fx:['moon', 'smoke'], pal:[0xf4f4f8, 0xc0c8d8, 0x9aa0b0, 0xe8f0ff], glow:0xe8f0ff}, {origin:'Lunar Avatar (homage)', lore:'The fist of a moon god who would not let his avatar die. The wraps are whiter than any night.', abil:[['regen', 5], ['counter', 30], ['vengeance', 6]], down:['fragile', 8]}),
  A('titan_battle_plate', 'Battle-Plate of the Mad Titan', 'plate', O, [], {h:'titan', eye:0xffe060, sh:'round', ch:'plate', sk:'tassets', ar:'gemgauntlet', lg:'plate', cape:['none'], fx:['gems6'], pal:[0xd8a838, 0x2a3a9a, 0x6a4a9a, 0xffe060], glow:0xffe060, skin:0x8a6aa8}, {origin:'Mad Titan (homage)', lore:'Six stones, one snap. The plate was made to survive the hand that wears it.', abil:[['ward', 25], ['thorns', 30], ['amp', 10]], down:['clumsy', 8]}),
  A('eldritch_cloak', 'Vestments of the Sorcerer Supreme', 'robe', O, [], {h:'none', hair:0x2a2420, eye:0x7fff60, sh:'collar', ch:'robe', em:'amulet', sk:'robe', ar:'cloth', lg:'boots', cape:['cloak', 0xc01818, 0xffcf4a], fx:['mandala', 'runes'], pal:[0x1a2a6a, 0xffcf4a, 0xc01818, 0x7fff60], glow:0xffa040}, {origin:'Sorcerer Supreme (homage)', lore:'A cloak with a mind of its own and an eye that can turn back time. It chose you.', abil:[['regen', 6], ['mend', 3], ['energize', 10]], down:['maxhp', 8]}),
  A('praetor_suit', 'Hell-Walker’s Leathers', 'leather', O, [], {h:'flameskull', eye:0xff6020, sh:'spike', ch:'leather', sk:'coat', ar:'bracer', lg:'boots', cape:['none'], fx:['chains', 'flames'], pal:[0x1a1414, 0x8a8a90, 0x0e0a0a, 0xff6020], glow:0xff6020}, {origin:'Hell-Walker (homage)', lore:'A rider bound to a demon of vengeance. Look into his eyes, and feel every pain you ever caused.', abil:[['evasion', 16], ['thorns', 35], ['vengeance', 8]], down:['bleed', 3]}),
  A('mantle_dark_phoenix', 'Mantle of the Dark Phoenix', 'robe', O, [], {h:'none', hair:0xc02010, eye:0xffa020, sh:'none', ch:'robe', em:'firebird', sk:'robe', ar:'bracer', lg:'boots', cape:['wings', 0xff4010, 0xffcf4a], fx:['flames', 'aura'], pal:[0xc01818, 0xffcf4a, 0x6a0a0a, 0xffa020], glow:0xffa020}, {origin:'Cosmic Firebird (homage)', lore:'The force of life and death, burning in a mortal heart. It hungers.', abil:[['regen', 5], ['phoenix', 50], ['amp', 10]], down:['selfburn', 10]}),
  A('shroud_starspawn', 'Shroud of the Drowned Dreamer', 'robe', O, [], {h:'tentacleface', eye:0x40ffb0, sh:'fin', ch:'robe', sk:'robe', ar:'claw', lg:'cloth', cape:['wings', 0x1a3a2a, 0x40ffb0], fx:['tentacles', 'bubbles'], pal:[0x2a5a3a, 0x40ffb0, 0x0e2014, 0x9affd8], glow:0x40ffb0}, {origin:'Elder Deep (homage)', lore:'In his house at R’lyeh, he waits dreaming. The shroud dreams too: of you, waking.', abil:[['regen', 5], ['weaken', 30], ['ward', 15]], down:['tired', 6]}),
  A('devourer_regalia', 'Regalia of the Devourer', 'plate', O, [], {h:'devourer', eye:0x9fe8ff, sh:'round', ch:'plate', em:'w', sk:'tassets', ar:'gauntlet', lg:'plate', cape:['none'], fx:['aura', 'stars'], pal:[0x6a2a8a, 0x2a4aa0, 0x3a1a5a, 0x9fe8ff], glow:0x9fe8ff}, {origin:'World-Eater (homage)', lore:'The last survivor of the universe before this one. It eats worlds because it must.', abil:[['ward', 22], ['regen', 4], ['taunt', 40]], down:['clumsy', 8]}),
  A('silver_instinct_gi', 'Gi of Silent Instinct', 'leather', O, [], {h:'none', hair:0xdfe6ee, eye:0xdfe6ee, sh:'none', ch:'gi', sk:'none', ar:'bracer', lg:'boots', cape:['none'], fx:['aura', 'wind'], pal:[0xe86a10, 0x1a3a8a, 0x1a3a8a, 0xdfe6ee], glow:0xdfe6ee}, {origin:'Silent Instinct (homage)', lore:'The body moves without the mind. The fighter never needed armour: only to stop thinking.', abil:[['evasion', 22], ['counter', 40], ['critdmg', 40]], down:['fragile', 10]}),
  A('symbiote_maw', 'Symbiote Maw', 'leather', O, [], {h:'symbiote', eye:0xffffff, sh:'spike', ch:'scale', sk:'none', ar:'claw', lg:'plate', cape:['none'], fx:['eyes', 'teeth', 'tentacles'], pal:[0x1a1238, 0x6a1a5a, 0x0a0618, 0xffffff], glow:0xb040ff}, {origin:'The Hungry Dark (homage)', lore:'It is not a suit. It is alive, it is hungry, and it has a great many eyes.', abil:[['evasion', 16], ['lifesteal', 12], ['counter', 35]], down:['bleed', 3]}),
  A('apokolips_plate', 'Granite Plate of the Omega Tyrant', 'plate', O, [], {h:'granite', eye:0xff3010, sh:'layer', ch:'plate', em:'omega', sk:'tassets', ar:'gauntlet', lg:'plate', cape:['none'], fx:['omega'], pal:[0x4a4a50, 0x2a3a6a, 0x1a1a24, 0xff3010], glow:0xff3010, skin:0x5a5a60}, {origin:'Fire-Pit Tyrant (homage)', lore:'Lord of a burning world, hunting the equation that ends free will. His eyes fire beams that follow you.', abil:[['ward', 24], ['thorns', 30], ['bulwark', 10]], down:['tired', 6]}),
  A('herald_chrome', 'Chrome of the Silver Herald', 'leather', O, [], {h:'none', hair:0xe8eef6, eye:0xe8eef6, sh:'none', ch:'chrome', sk:'none', ar:'cloth', lg:'cloth', cape:['none'], fx:['board', 'stars'], pal:[0xe8eef6, 0xc8d8e8, 0xb0c0d0, 0x9fe8ff], glow:0x9fe8ff, skin:0xe8eef6}, {origin:'Cosmic Herald (homage)', lore:'He traded his freedom to save his world, and rides the cosmos ahead of the Devourer.', abil:[['evasion', 24], ['energize', 10], ['regen', 3]], down:['fragile', 10]}),
  A('doom_mask', 'Iron Mask of the Doom Emperor', 'plate', O, [], {h:'ironmask', eye:0x7fff60, sh:'round', ch:'plate', sk:'tunic', ar:'gauntlet', lg:'plate', cape:['cloak', 0x1a5a2a, 0x2a7a3a], fx:['runes'], pal:[0x7a808a, 0x2a7a3a, 0x1a4a22, 0x7fff60], glow:0x7fff60}, {origin:'Iron Monarch (homage)', lore:'Science and sorcery bolted into one iron face. He bows to no one, and neither does the mask.', abil:[['ward', 20], ['regen', 4], ['amp', 10]], down:['maxhp', 6]}),
  A('tower_lord_plate', 'Plate of the Dark Lord of the Tower', 'plate', O, [], {h:'spikecrown', eye:0xff8020, sh:'spike', ch:'plate', sk:'tassets', ar:'claw', lg:'plate', cape:['tattered', 0x0e0a0a], fx:['spikes', 'eye'], pal:[0x1a1616, 0x3a2a24, 0x0e0a0a, 0xff8020], glow:0xff8020}, {origin:'Lidless Eye (homage)', lore:'One armour to rule them all. Its maker poured his cruelty into the steel, and it still watches.', abil:[['ward', 22], ['thorns', 35], ['taunt', 30]], down:['clumsy', 8]})];

// the black swordsman's blade, to go with his armour: 110 Attack and no Sp. Atk at all
D.LEGENDS.push(['dragonslayer_sword', 'Dragon Slayer', 'weapon', 'heavy', 4, 'Dragon slayer', 'Too big to be called a sword: massive, thick, heavy and far too rough. More like a heap of raw iron.', [['crit', 15], ['vengeance', 5]], null, 'blood', {b:'sword', slab:1, L:3.1, wd:0.56, guard:'cross', metal:0x55575e, edge:0x9a9ca4, accent:0x3a2a1a, rune:0xff2020}]);
D.LEGEND_BS = {dragonslayer_sword:{atk:110, spa:0}};
D.ARMOURS = BASE.concat(EPIC, MYTHS, OUTER);
D.ARMOUR_BY = Object.fromEntries(D.ARMOURS.map(a => [a.key, a]));
D.ITEM_TYPES = Object.assign(D.ITEM_TYPES || {}, {symbiote_maw:['cosmic', 'dark'], apokolips_plate:['cosmic', 'rock'], herald_chrome:['cosmic', 'steel'], doom_mask:['cosmic', 'steel'], tower_lord_plate:['cosmic', 'dark'],
  pendragon:['steel', 'dragon'], greenknight:['grass'], morrigan:['dark', 'flying'], riastrad:['fighting', 'dark'], atlantean:['water', 'steel'], selkie:['water'], leviathan:['water', 'dragon'], sirenqueen:['water', 'fairy'],
  anubis:['ghost', 'ground'], pharaoh:['fire', 'ground'], ra:['fire', 'psychic'], apophis:['poison', 'dark'], einherjar:['steel', 'ice'], valkyrie:['flying', 'fighting'], allfather:['psychic', 'ice'], fenrir:['dark', 'ice'],
  onikabuto:['steel', 'fighting'], kitsune:['fire', 'psychic'], susanoo:['electric', 'dragon'], raijin:['electric', 'fighting'], achilles:['steel', 'fighting'], nemean:['normal', 'fighting'], hades:['ghost', 'dark'], zeus:['electric', 'flying'],
  dragonslayer:['steel', 'dark'], dreadhorn:['dark', 'steel'], sunforged:['fire', 'steel'], obsidian:['rock', 'fire'], stormcaller:['electric', 'steel'], bloodmoon:['dark', 'fighting'], nightstalker:['dark'], venomfang:['poison'],
  frostfang:['ice'], windrunner:['flying'], crimsoncorsair:['water', 'fighting'], arcanist:['psychic'], embersage:['fire'], tidecaller:['water'], voidweave:['ghost', 'psychic'], starlit:['fairy', 'psychic']});
// pools: which designs drop where
const TIER_RAR = {base:[0, 1, 2], epic:[3], legend:[4], myth:[5], outer:[6]};
D.armourPool = (land, rar) => D.ARMOURS.filter(a => TIER_RAR[a.tier].includes(rar) && (a.tier === 'outer' || !a.lands.length || a.lands.includes(land)));
D.armourName = (a, rar) => a.tier === 'base' ? `${D.BASE_TIER[rar].pre[a.role === 'plate' ? 0 : a.role === 'leather' ? 1 : 2]} ${a.name}` : a.name;
})();
